### ISSUE TITLE
Dave's Whiterun in BSA Textures Not Loading Correctly. 

### ISSUE THREAD

**Issue by InfiniteMaximum** [jdsmith2816/eldersouls#10]
**Describe the bug**
Issue with Daves Whiterun in BSA format. Issue with textures not rendering correctly on some buildings, appearing as blue. Getting close fixes it, but reappears upon returning to location.

**To Reproduce**

Go to Whiterun from Riverwood. Then take a look at the buildings, should be obvious. 

**Expected behavior**
Textures should not appear missing and should render correctly. 

**Screenshots**
Example, at the stable. 
https://cdn.discordapp.com/attachments/704708621732151547/704895374460059668/unknown.png

**Modlist version**
V 1.0.0

**Did you add any additional mods?**
No, ini settings were left as default. Using the ones attached to the MO2 profile provided.

**Comment by jdsmith2816** [comment]
Dave's Whiterun is no longer BSA'd in update.

Fixed for 1.0.2
