### ISSUE TITLE
CTD When Applying Poisons

### ISSUE THREAD

**Issue by Shanomatic** [jdsmith2816/eldersouls#100]
**Describe the bug**
A crash to desktop when applying poisons to weapons. This was tested with five different poisons on five different weapons.

**To Reproduce**

1. Apply poison to weapon
2. Experience crash

**Expected behavior**
The game shouldn't crash. 

**Screenshots**
No crash log was generated, for whatever reason.

**Modlist version**
1.1.7
**Did you add any additional mods?**
No

**Comment by TheOriginalGeez** [comment]
I can confirm this.

**Comment by jdsmith2816** [comment]
Please disable the `Best In Class Plus Plus` mod and let me know if the problem resolves itself. @TheOriginalGeez  @Shanomatic

**Comment by TheOriginalGeez** [comment]
@jdsmith2816 It seems that Best In Class Plus Plus is the culprit.

**Comment by jdsmith2816** [comment]
Thanks.  I removed it for next update.
