### ISSUE TITLE
Trapdoor for 'Revenants of the Forbidden Order' Inaccessible

### ISSUE THREAD

**Issue by SWIFT31S** [jdsmith2816/eldersouls#108]
The trapdoor to get to the armour from 'Revenants of the Forbidden Order' is clipped off by the terrain added by 'The Great Town of Karthwasten'. A potential fix for this would be to use the RotFO patch that moves the trapdoor entrance into Karthwasten Hall instead. 

![20200527051514_1](https://user-images.githubusercontent.com/65710674/82979755-c6cbf480-9fdf-11ea-9e2a-762343eb42cc.jpg)
![20200527051522_1](https://user-images.githubusercontent.com/65710674/82979756-c7648b00-9fdf-11ea-9c53-4bea6086d458.jpg)

**Comment by jdsmith2816** [comment]
Thanks.  That patch didn't exist when I installed this and I failed to notice the trapdoor being out of place.  I'll get this fixed for next update.

**Comment by jdsmith2816** [comment]
Fixed in 1.3
