### ISSUE TITLE
NPC missing hands 

### ISSUE THREAD

**Issue by Pepin90** [jdsmith2816/eldersouls#114]
**Describe the bug**
Tilma the haggard in the house of the companions has no hands. 

**Modlist version**
Elder Souls last version 1.1.8

**Did you add any additional mods?**
Nothing related to npcs, armours and clothings. 
Nothing related to npcs bodies. 

See the screenshot in the bottom part. It isn't very clear but you can't see the old woman hands. Kodlak's dinner may be problematic... 

![ScreenShot6](https://user-images.githubusercontent.com/65945826/83309299-2eb15380-a209-11ea-8b22-49383d2b48df.png)
![Screenshot_20200529-233801](https://user-images.githubusercontent.com/65945826/83309323-3c66d900-a209-11ea-8424-bfafff9f6181.jpg)

**Comment by jdsmith2816** [comment]
This is already fixed in latest installer.
