### ISSUE TITLE
Thornrock DragonPriest Mask Displays Broken

### ISSUE THREAD

**Issue by SWIFT31S** [jdsmith2816/eldersouls#116]
**Describe the bug**
The Dragon Priest mask displays inside Thornrock (Playerhome outside Whiterun) do not return the masks to your inventory upon taking them off the display.

**To Reproduce**
1. Go to Thornrock
2. Place Dragon Priest mask on display
3. Activate mask display again to remove mask from display
4. Mask is removed from display but not returned to player's inventory

**Expected behavior**
Mask should be returned to player's inventory

**Modlist version**
1.1.7

**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 1.3
