### ISSUE TITLE
Hole in the world in Shore’s stone

### ISSUE THREAD

**Issue by Asmondar** [jdsmith2816/eldersouls#131]
**Describe the bug**
Under the inn, in Shore’s stone I have a floating piece of dirt with a hole in the world.

**To Reproduce**

1. Go to '...' Shore stone.
2. Do '...'

**Expected behavior**
No hole?

**Screenshots*

![7B953C00-1AAC-42FB-9593-7B4EA2C7D158](https://user-images.githubusercontent.com/67242048/85234696-35cd1b00-b3dd-11ea-8aec-e1e036276ead.jpeg)

**Modlist version**
Elder Souls
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 1.3
