### ISSUE TITLE
Pale, white hands

### ISSUE THREAD

**Issue by Duxter7** [jdsmith2816/eldersouls#133]
**Describe the bug**
I have pale hands in the first person view whenever I create a character (for this issue I take a screenshot of Breton, Preset 4 with minor changes)

**To Reproduce**
Create a character (I have found the same issue previously and the author there stated that all races are affected:

**Expected behavior**
The same color of hands as in third person view

**Screenshots**

![ScreenShot9](https://user-images.githubusercontent.com/26548172/85589679-2eb44000-b65d-11ea-8f34-d76f26644b72.png)
![ScreenShot8](https://user-images.githubusercontent.com/26548172/85589689-31169a00-b65d-11ea-8f26-71e64f225810.png)

**Modlist version**
1.1.13
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 1.3
