### ISSUE TITLE
Missing texture rocks near Seaspoint Settlement

### ISSUE THREAD

**Issue by Cygnall** [jdsmith2816/eldersouls#136]
Missing texture in Seapoint Settlement, asset information provided in screenshot.

![SkyrimSE_tno5lC646I](https://user-images.githubusercontent.com/31330700/85781151-62da4000-b6f3-11ea-8fd3-9d146eb30d82.jpg)

**Comment by Cygnall** [comment]
I also found a floating tree nearby.

![image](https://user-images.githubusercontent.com/31330700/85781638-e85df000-b6f3-11ea-84ee-708fcd4e097c.png)

**Comment by Cygnall** [comment]
And another, dang.

![image](https://user-images.githubusercontent.com/31330700/85781775-0a577280-b6f4-11ea-99af-785cb80a2a95.png)

**Comment by Cygnall** [comment]
... And another.
![image](https://user-images.githubusercontent.com/31330700/85782054-54d8ef00-b6f4-11ea-84d9-d045b1a40f00.png)

**Comment by Cygnall** [comment]
I've continued to find more but there are just too many to list.

**Comment by jdsmith2816** [comment]
Fixed in 1.3
