### ISSUE TITLE
Executioner Perk available too early

### ISSUE THREAD

**Issue by Cygnall** [jdsmith2816/eldersouls#138]
**Describe the bug**
Executioner Perk available too early.

**To Reproduce**

Get Heavy Armor high enough to unlock "Devastating Blow".
Look up the tree.

**Expected behavior**
Executioner shouldn't unlock until 90.

**Screenshots**
![image](https://user-images.githubusercontent.com/31330700/85804180-f8d39200-b716-11ea-99e1-e41dd2ac1982.png)

**Modlist version**
v1.1.13

**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment]
Fixed in 1.3
