### ISSUE TITLE
Plethora of Seapoint Settlement Problems (Formerly Stalls in Seapoint Settlement disappearing at night and not reappearing in the day)

### ISSUE THREAD

**Issue by Cygnall** [jdsmith2816/eldersouls#139]
**Describe the bug**
During the day, the shop stalls in Seapoint Settlement are active. They disappear at night and then do not come back the next day.

**To Reproduce**

1. Go to 'Seapoint Settlement for the first time.'
2. Wait until night.
3. Wait until the next day.

**Expected behavior**
The shopkeep stalls should come back.

**Screenshots**
First Day, first visit
![image](https://user-images.githubusercontent.com/31330700/85805278-e27b0580-b719-11ea-823b-929041660dd1.png)
Second Day
![image](https://user-images.githubusercontent.com/31330700/85805260-d55e1680-b719-11ea-9368-606f0f8b7ff9.png)

**Modlist version**
v1.1.13

**Did you add any additional mods?**
No.

**Comment by Cygnall** [comment]
Sidenote: NPC pathing in the area is really broken. They run into and get caught on scenery and buildings a _lot_.

**Comment by Cygnall** [comment]
The bad pathing at work.

![image](https://user-images.githubusercontent.com/31330700/85828392-50ddb900-b756-11ea-874b-c797a0323b29.png)

**Comment by Cygnall** [comment]
Lector's lodge nearby - If you try to fast travel, it won't let you until you get closer to town.

![image](https://user-images.githubusercontent.com/31330700/85884679-03426a00-b7b1-11ea-85a3-83860a1c3a2e.png)

**Comment by jdsmith2816** [comment]
Fixed in 1.3
