### ISSUE TITLE
Bugged door in Helgen

### ISSUE THREAD

**Issue by Monica-21** [jdsmith2816/eldersouls#14]
**Describe the bug**
The door that Ralof takes through at Helgen Keep is bugged. It looks like overlapping doors.

**To Reproduce**

1. Go to Helgen
2. Look at door

**Expected behavior**
Its appearance should match the door that Hadvar takes you through.

**Screenshots**
https://i.imgur.com/KqVvEgr.png

**Modlist version**

1.0.1

**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed for 1.0.2
