### ISSUE TITLE
Faralda (College Entry Trail NPC) will not speak, cant join college

### ISSUE THREAD

**Issue by Fenrir4242** [jdsmith2816/eldersouls#140]
**Describe the bug**

Faralda (Base ID: 0001C197, Ref ID: 0001C1A5)
On activating Faralda game will proceed as if you are in conversation (HUD fades, movement and turning slowed), but she will not speak. Sometimes pressing "E" or clicking/Tabbing can exit the convo. Three times I was unable to exit this conversation mode. I walked to the gate of the college and was still in conversation. 

Resolved by Console Kill Faralda, then Resurrect, but NPC remains broken after Resurrect 

**To Reproduce**

Unknown, though character was also experiencing the unable to level glitch. This was my first character to get to the college, basically went:
Straight from Black Reach start (Necro lair) ---> Windhelm to try to sleep (couldnt level so was trying multiple beds) ---> Straight to the College

**Modlist version**
1.1.13

**Did you add any additional mods?**
No, fresh install of SSE as well

**Comment by jdsmith2816** [comment]
Fixed in 1.3.1
