### ISSUE TITLE
New list of visual bugs

### ISSUE THREAD

**Issue by Cygnall** [jdsmith2816/eldersouls#141]
Beehive in Riften
![image](https://user-images.githubusercontent.com/31330700/85828817-38ba6980-b757-11ea-84e2-bac8b4805364.png)

**Comment by Cygnall** [comment]
Floating bush along the road outside Riften
![image](https://user-images.githubusercontent.com/31330700/85829437-9dc28f00-b758-11ea-9826-b47a4d73f5ae.png)

**Comment by Cygnall** [comment]
Floating fence outside Riften
![image](https://user-images.githubusercontent.com/31330700/85829484-b5017c80-b758-11ea-894c-ac8bfa86b5cc.png)

**Comment by Cygnall** [comment]
Floating tree in Ivarstead
![image](https://user-images.githubusercontent.com/31330700/85830179-2beb4500-b75a-11ea-8041-a88c7a517738.png)

**Comment by Cygnall** [comment]
Kinda unrelated to visual bugs, but NPCs are getting stuck on this fence in Riften. Pathing?
![image](https://user-images.githubusercontent.com/31330700/85830391-82f11a00-b75a-11ea-86e7-555e8cbafdcd.png)

**Comment by Cygnall** [comment]
Weird mesh issue
![image](https://user-images.githubusercontent.com/31330700/85878056-21569d00-b7a6-11ea-8ef4-ab5bceded8c3.png)

**Comment by Cygnall** [comment]
Floating lantern and pole Goldenrock Mine
![image](https://user-images.githubusercontent.com/31330700/85881424-91b3ed00-b7ab-11ea-8937-2a292cc0443d.png)

**Comment by Cygnall** [comment]
Floating snow in Old Hrothgar
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 06 26 - 16 32 47 80](https://user-images.githubusercontent.com/31330700/85898717-c8e5c680-b7ca-11ea-850f-34da8234dcf7.png)
Couldn't highlight the snow itself, highlighted the lamp over it

**Comment by Cygnall** [comment]
Floating Tree near Karthwastern
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 06 26 - 17 55 38 11](https://user-images.githubusercontent.com/31330700/85904287-4c58e500-b7d6-11ea-8228-c72ed0cb3deb.png)

**Comment by Cygnall** [comment]
Missing texture on the sides of the logs. Not the main texture, the flat bits on the side.
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 06 26 - 18 01 07 88](https://user-images.githubusercontent.com/31330700/85904582-2122c580-b7d7-11ea-937d-5a1619466b67.png)

**Comment by jdsmith2816** [comment]
Fixed in 1.3.1
