### ISSUE TITLE
No audible dialogue wandering merchant

### ISSUE THREAD

**Issue by Cygnall** [jdsmith2816/eldersouls#142]
**Describe the bug**
This NPC has no audible dialogue.

![image](https://user-images.githubusercontent.com/31330700/85885718-cd05ea00-b7b2-11ea-91e1-b0d32db7023e.png)

v1.1.13

**Comment by SovnSkyrim** [comment]
The whole town of Coldhaven doesnt actually have audio.

**Comment by jdsmith2816** [comment]
Fixed in 1.3
