### ISSUE TITLE
Broken Mesh Certain Female NPCs also Khajiit Feet

### ISSUE THREAD

**Issue by Cygnall** [jdsmith2816/eldersouls#145]
**Describe the bug**
Certain Female NPCs appear to be using the right textures on the wrong mesh.

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 06 27 - 03 10 31 73](https://user-images.githubusercontent.com/31330700/85916996-16dae880-b824-11ea-8a8c-76cda4e029f1.png)

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 06 27 - 03 10 18 52](https://user-images.githubusercontent.com/31330700/85916992-117d9e00-b824-11ea-8ac8-6655d91777da.png)

After searching through the console this is the only one I could find, but would imagine others from the same .esp might be borked.

**Comment by Cygnall** [comment]
Also, Khajiit feet are broken because probably SkySight Custom Feet Mesh and trying to apply a vanilla texture to a custom mesh.

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 06 27 - 02 40 49 13](https://user-images.githubusercontent.com/31330700/85917027-6caf9080-b824-11ea-9cfd-e375509e7f0c.png)

**Comment by jdsmith2816** [comment]
Fixed in 1.3
