### ISSUE TITLE
Most books/letters are blank

### ISSUE THREAD

**Issue by Fenrir4242** [jdsmith2816/eldersouls#147]
**Describe the bug**
About 70% of books or letters I open contain no text. It happens with modded text and vanilla text. Trying to reread the book doesnt change what it shown (whether blank or the correct text - ie i cant break a working book and cant fix a broken one)

Problem persists across characters.

**To Reproduce**

Unknown - seems to be random which ones work 

**Modlist version**

No

**Comment by jdsmith2816** [comment]
Fixed in 1.3
