### ISSUE TITLE
Purple face texture on Balimund

### ISSUE THREAD

**Issue by Monica-21** [jdsmith2816/eldersouls#15]
**Describe the bug**
Balimund in Riften appears to have a missing facepaint texture

**To Reproduce**

1. Go to Riften
2. Look at Balimun

**Expected behavior**
That half his face would not be light purple.

**Screenshots**
https://i.imgur.com/1oVNbtW.png
https://i.imgur.com/d0EKxFU.png

**Modlist version**
1.0.1

**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 1.0.2
