### ISSUE TITLE
Problem with Face & Neck Colour with Nirelada Bluestone

### ISSUE THREAD

**Issue by bruhwtfxd** [jdsmith2816/eldersouls#150]
Nirelada Bluestone's  (the housecarl of Ulfric) has a different  Face & Neck colour than the rest of her body.

![ScreenShot4](https://user-images.githubusercontent.com/57353684/86867021-bc227600-c0da-11ea-98ee-3f89be70cb92.png)

the only mod that i enabled is the Simple Lock-On SE Mod.

**Comment by jdsmith2816** [comment]
Fixed in 1.3
