### ISSUE TITLE
I found a fix for the archery post bug. 

### ISSUE THREAD

**Issue by darkpeep** [jdsmith2816/eldersouls#151]
**Describe the bug**
There is a bug on the archery posts at the end of the wooden logs where the is a missing texture.
It is caused by Skyrim 2020 Parallax by PFUSCHER.
There is a fix within the downloads section of that mod on the nexus website called "Fix Archery Target"
https://www.nexusmods.com/skyrimspecialedition/mods/2347?tab=files&BH=1
**To Reproduce**
1. Go to 'any archery post and see if the end of the logs of wood having missing purple textures.'
2. Do 'Do what was said previously.'

**Expected behavior**
There is supposed to be a texture for the archery post.

**Screenshots**

**Modlist version**
1.1.13
**Did you add any additional mods?**
Not while it was happening, fixed with an additional mod on the official mod that is causing it.

**Comment by darkpeep** [comment]
Make sure the priority for it is set to 392 or you will get a ctd upon loading

**Comment by darkpeep** [comment]
![enb2020_7_10_20_52_25](https://user-images.githubusercontent.com/68132832/87212987-91f5d180-c2ef-11ea-9fc8-450399285d81.png)

**Comment by lexcia98** [comment]
Fixed in an update, closing old issues that have been fixed.
