### ISSUE TITLE
Issues with Leveling Up

### ISSUE THREAD

**Issue by Since28** [jdsmith2816/eldersouls#156]
Hello i have some issues with your Level system. I played for a few hours yesterday and everything worked fine. But after i leveled up my caracter a few times it broke. Now it always says i need 407 Gold for my next level up but i have 3k. Any Ideas on how to fix this? I love this Modpack but this bug sadly makes it unplayable. 

I will provide you with the steps to recreate this bug:
1. Sleep with enough Gold for a level up
2. Dont Spend al of your Gold
3. Exit the level up Menu
-> It still works fine
4. Sleep again
5. Spend all of your Gold
-> And now it is broken
6. Sleep with enough Gold
7. The Menu doesnt appear and the Messsage pops up

I hope you can recreate this Issue and find a fix.
Thanks

**Comment by lexcia98** [comment]
Fixed in an update a day after this comment. Sorry I didn't reply sooner.
