### ISSUE TITLE
blackface , store bug on a Build your noble house mod shopkeeper

### ISSUE THREAD

**Issue by askovtheone** [jdsmith2816/eldersouls#157]
**Describe the bug**
Alchemist Helda 
Base:b4180f4f
Ref: b4180f50
from Build your noble house has a blackface bug
along with unable to sell or buy any ingredient or potion/posion in store

**To Reproduce**
1.Go to Fellburg in Falkreath
2.Build the alchemist store and it will spawn the store and Helda inside

**Expected behavior**
Helda with blackface bug , she is able to engage in dialodge with me, but you will not able to sell or buy ingredient and potion/posion in the store page.
the tabs are simplly grey out.

**Screenshots**
![ScreenShot5](https://user-images.githubusercontent.com/68938050/88758251-8da83000-d19a-11ea-8fc0-a94464f57859.png)

unable to screencap the store page or the console even with Greenshot , sorry.
**Modlist version**
1.1.15
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Resolved in 1.3
