### ISSUE TITLE
Werewolves are invisible

### ISSUE THREAD

**Issue by darkpeep** [jdsmith2816/eldersouls#158]
**Describe the bug**
During Proving Honor, when Farkas turned into a werewolf, he was invisible, and during The Silver Hand, when I go to see Aela to become a werewolf, she is also invisible. 
**To Reproduce**
Start Proving Honor and continue to the part of the quest where Farkas turns into a werewolf or start The Silver Hand,
and go to the Skyforges hidden place to become a werewolf, and Aela will be invisible.

**Expected behavior**
The companions are supposed to be visible and I'm assuming other werewolves are invisible too. My character is normal though when I tested it in the Proving Honor quest by saving with an elder scroll and giving myself beast blood. I reloaded the save so I didn't have it so I could get beast blood when I progress through the quest.

**Screenshots**
(https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.
![enb2020_7_31_10_45_09](https://user-images.githubusercontent.com/68132832/89047343-48137080-d31c-11ea-9504-5b0f26c0274b.png)
![enb2020_7_31_10_55_08](https://user-images.githubusercontent.com/68132832/89047384-5497c900-d31c-11ea-8f3d-fe519c1cc724.png)

I am unable to click on Aela in the picture, shes invisible but maybe there is not even a model I guess.
**Modlist version**
1.1.16

**Did you add any additional mods?**
Combat Gameplay Overhaul although this bug was here before I added that considering there is an open bug report about this already that was supposed to be fixed in 1.1.7 and it wasn't nor was it stated it was fixed in that versions changelog.

**Comment by lexcia98** [comment]
> ![enb2020_7_31_11_07_17](https://user-images.githubusercontent.com/68132832/89048609-0e436980-d31e-11ea-8874-e1b27fda8362.png)
> 
> she appears here, so I am going to assume it just has to do with the two quests being bugged during those segments.

Where is that? Was that just her changing during normal gameplay and not part of a quest? If so I think I might know what to do. Thank you.

**Comment by darkpeep** [comment]
@lexcia98 That was during the silver hand quest but sometimes the animation would bug out and cause her body to be elongated but pretty much normal gameplay I assume.

**Comment by jdsmith2816** [comment]
Fixed in1 .3
