### ISSUE TITLE
Floating tree outside Solitude

### ISSUE THREAD

**Issue by Cygnall** [jdsmith2816/eldersouls#16]
**Describe the bug**
There's a tree floating as you walk down the road.

**To Reproduce**

1. Exit Solitude.
2. Walk down the road.
3. It's on the left.
4. Specific tree pictured below.

**Expected behavior**
The tree should not be floating.

**Screenshots**
https://i.imgur.com/vk2dhab.jpg

**Modlist version**
1.0.1

**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment]
Fixed in 1.0.2
