### ISSUE TITLE
Proto-rifle bullet bug

### ISSUE THREAD

**Issue by Epyrus1991** [jdsmith2816/eldersouls#162]
**Describe the bug**
A bullet is stuck in the character as is it wearing the hunter's rifle, I think it comes from Glenmoril (the one with armor piercing), just near the guardian stones in the hunter's camp, the npc there is wearing it.

**To Reproduce**
Equip and remove a hunting rifle.

**Expected behavior**
Expected to not see a flying bullet always in front of me I guess.

**Screenshots**

![Inkedenb2020_8_14_22_08_46_LI](https://user-images.githubusercontent.com/69695995/90289012-41880b80-de7b-11ea-8263-9ed095ba1b7e.jpg)

**Modlist version**
1.2.0.1
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 1.3
