### ISSUE TITLE
Mismatched face and body skin tone

### ISSUE THREAD

**Issue by Rpkiller1** [jdsmith2816/eldersouls#163]
**Describe the bug**
Mismatched face and body on Ranmir in Winterhold, Ganna Uriel, Roggi Knot-Beard, Ilfhild, Jurgan, Erarik in Kynesgrove
in Kynesgrove.

**To Reproduce**

2. Do '...'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

![SkyrimSE_HYnpZd43uP](https://user-images.githubusercontent.com/69942286/90701300-0e1bf700-e256-11ea-965d-6ac58c8bbbe4.jpg)

![SkyrimSE_sV07BYqOYj](https://user-images.githubusercontent.com/69942286/90704897-b2ef0200-e25f-11ea-9099-8605eec91edd.jpg)

![SkyrimSE_5LJ6oZp2jX](https://user-images.githubusercontent.com/69942286/90704918-be422d80-e25f-11ea-93ae-b85530fb1cb6.jpg)

![SkyrimSE_jbPPTvZPWs](https://user-images.githubusercontent.com/69942286/90704922-c4380e80-e25f-11ea-8398-9775fefda61a.jpg)

![SkyrimSE_PMohGVjQpA](https://user-images.githubusercontent.com/69942286/90704930-c8fcc280-e25f-11ea-9e79-5aec07b4cb08.jpg)

![SkyrimSE_NSN8pUSRCZ](https://user-images.githubusercontent.com/69942286/90704941-d023d080-e25f-11ea-91fe-b1214332059d.jpg)

**Modlist version** 
1.2.0.1

**Did you add any additional mods?**
None

**Comment by lexcia98** [comment]
Fixed a lot if black face bugs in the next update.

**Comment by jdsmith2816** [comment]
Fixed in 1.3
