### ISSUE TITLE
Helgi and Laelette load order placement causing issues with morthal.

### ISSUE THREAD

**Issue by zediious** [jdsmith2816/eldersouls#165]
**Describe the bug**
Morthal is a mess due to conflicts with cities of the north

**To Reproduce**
load the game

1. Go to '...' morthal
2. Do '...' look around

**Expected behavior**
multiple buildings not clipping and doors in the correct locations.

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**

**Did you add any additional mods?**
no

You simply need to move findiong helgi and laelette.esp before COTN- Morthal in the packaged loadorder.txt to fix this issue. There are also a number of other odd banner placements, etc that need to be corrected via patches. Loving the modpack, just want to help iron out some things :)

**Comment by zediious** [comment]
There seems to be quite a few issues with some cities and floating objects as detailed in other issue threads, I managed to fix morthal with the aforementioned fix and removing JK's skyrim records from the town with xedit. I plan to continue to do this with anything I come across.

**Comment by zediious** [comment]
To close this, I recommend going through the cities merge and cleaning up some things. COTN now has winterhold done as well so you could replace ETAC with that.

**Comment by zediious** [comment]
Also, unless you've fixed these issues in the update they certainly were still present.

**Comment by jdsmith2816** [comment]
1.3 has not yet been released
