### ISSUE TITLE
Remove ETAC - Winterhold and replace with COTN - Winterhold

### ISSUE THREAD

**Issue by zediious** [jdsmith2816/eldersouls#166]
**Request**
Cities of the North - Winterhold was released recently and I've added in into my game in place of ETAC - Winterhold safely. It fits very well, and I would recommend the switch. I could create a patch between the two if this is something you would be interested in.

**Additional context**

**Comment by jdsmith2816** [comment]
Fixed in 1.3

**Comment by zediious** [comment]
> 
> 
> Fixed in 1.3

Good to hear! Glad you're still on this modlist :) It's a great one.
