### ISSUE TITLE
1.1.18 fails to install due to Wrye Bash

### ISSUE THREAD

**Issue by shazdeh** [jdsmith2816/eldersouls#167]
**Describe the bug**
Due to update to Wrye Bash mod, the installer fails.

**Screenshots**
![image](https://user-images.githubusercontent.com/854165/93646805-309f5c80-fa1c-11ea-8c56-f65d69cf7ed5.png)

**Modlist version**
1.1.18

**Comment by lexcia98** [comment]
Working on it right now.

**Comment by jdsmith2816** [comment]
Fixed in 1.3
