### ISSUE TITLE
Install failing due to incorrect hash

### ISSUE THREAD

**Issue by AndyGC** [jdsmith2816/eldersouls#168]
Northern Cathedral Grass seems to be acting up here, WJ says it failed to download despite the fact the file's been downloaded. Also mentions the hash so might be a mismatch, not 100% sure how to interpret the mixed messages.
Worth mentioning is that NCG has 1.8 and 1.9 on Nexus, while the file in question seems to be version 1.81 judging by the filename.

![image](https://user-images.githubusercontent.com/14154834/93692163-dc65ac80-faef-11ea-8a78-543f9dbc7f21.png)
![image](https://user-images.githubusercontent.com/14154834/93692204-7594c300-faf0-11ea-92e7-963ceeaae88e.png)

**Comment by lexcia98** [comment]
Compiling fix right now. Sorry for the problems with this update. Will be up either late tonight or early tomorrow.

**Comment by AndyGC** [comment]
No worries, checked the discord and saw it was mentioned in the chat as well with the version issue I suspected.
Thanks for the quick response and for getting on top of the issues so fast!
