### ISSUE TITLE
Black Face Bugs List

### ISSUE THREAD

**Issue by darkpeep** [jdsmith2816/eldersouls#169]
**Describe the bug**
Tons of Black Face Bugs

**To Reproduce**

1. Go to any of the locations in the screenshots
2. Look at the NPCS

**Expected behavior**
No black face bug.

**Screenshots**
Will be separating based on location
Location is basically at the edge of the map. I used the ship wreck start if you're wondering why I am there. Every NPC has a BFB there.
![enb2020_9_24_14_46_43](https://user-images.githubusercontent.com/68132832/94187010-63f74680-fe75-11ea-906e-9ab3ceb2276e.png)
![enb2020_9_24_14_46_02](https://user-images.githubusercontent.com/68132832/94187066-74a7bc80-fe75-11ea-8c36-eb449bd56744.png)

The Bashing Flagon:
![enb2020_9_24_14_55_23](https://user-images.githubusercontent.com/68132832/94187587-247d2a00-fe76-11ea-814a-848096e12ca3.png)
![enb2020_9_24_14_55_10](https://user-images.githubusercontent.com/68132832/94187602-29da7480-fe76-11ea-9ccb-71a478cb0988.png)
![enb2020_9_24_14_55_15](https://user-images.githubusercontent.com/68132832/94187615-3068ec00-fe76-11ea-9b5b-571ecb67099f.png)
![enb2020_9_24_14_57_49](https://user-images.githubusercontent.com/68132832/94187696-57bfb900-fe76-11ea-918e-e073f94b9103.png)

Bee and Barb in Riften:
![enb2020_9_24_14_59_07](https://user-images.githubusercontent.com/68132832/94189240-7d4dc200-fe78-11ea-8121-28ed3cc479b2.png)

**Modlist version**
Newest one that released on September 20th
**Did you add any additional mods?**
No.

**Comment by darkpeep** [comment]
**College of Winterhold:** 
![enb2020_9_24_15_22_13](https://user-images.githubusercontent.com/68132832/94193016-c6544500-fe7d-11ea-82c4-554a3e2195a1.png)

****Seapoint Settlement**:** 
Pretty much everyone here has a black face bug

![enb2020_9_24_15_28_07](https://user-images.githubusercontent.com/68132832/94193047-d2d89d80-fe7d-11ea-8e4f-a405e3d05fb2.png)
![enb2020_9_24_15_28_35](https://user-images.githubusercontent.com/68132832/94193099-eab02180-fe7d-11ea-820a-6eddd3e0473f.png)
![enb2020_9_24_15_28_39](https://user-images.githubusercontent.com/68132832/94193124-f1d72f80-fe7d-11ea-849b-a160e45eb5b5.png)
![enb2020_9_24_15_28_55](https://user-images.githubusercontent.com/68132832/94193133-f56ab680-fe7d-11ea-9e59-299dbf5d843b.png)
![enb2020_9_24_15_29_20](https://user-images.githubusercontent.com/68132832/94193166-00254b80-fe7e-11ea-92eb-0901df9ec8d6.png)
![enb2020_9_24_15_29_48](https://user-images.githubusercontent.com/68132832/94193178-01ef0f00-fe7e-11ea-8226-99c9f2039998.png)
![enb2020_9_24_15_30_35](https://user-images.githubusercontent.com/68132832/94193187-04e9ff80-fe7e-11ea-9a49-67c7259ed4e3.png)

****Palace of Kings (Windhelm)**:**
![enb2020_9_24_15_32_35](https://user-images.githubusercontent.com/68132832/94193239-1b905680-fe7e-11ea-816e-2a5b5f2398c4.png)
![enb2020_9_24_15_32_47](https://user-images.githubusercontent.com/68132832/94193251-1fbc7400-fe7e-11ea-898c-2f7925b62820.png)
![enb2020_9_24_15_32_57](https://user-images.githubusercontent.com/68132832/94193260-221ece00-fe7e-11ea-81c9-3c7f2c27f97e.png)
![enb2020_9_24_15_33_04](https://user-images.githubusercontent.com/68132832/94193269-24812800-fe7e-11ea-937b-a4c08a72889d.png)

****Morthal**:**
![enb2020_9_24_15_34_56](https://user-images.githubusercontent.com/68132832/94193294-2d71f980-fe7e-11ea-96dd-5fa72eeef166.png)
![enb2020_9_24_15_36_34](https://user-images.githubusercontent.com/68132832/94193385-49759b00-fe7e-11ea-859f-8b4980d7bf4f.png)
![enb2020_9_24_15_37_40](https://user-images.githubusercontent.com/68132832/94193392-4da1b880-fe7e-11ea-9300-85ca81983ca4.png)

****Markarth:**
![enb2020_9_24_15_40_11](https://user-images.githubusercontent.com/68132832/94193460-61e5b580-fe7e-11ea-9713-06bb711558bb.png)
![enb2020_9_24_15_40_36](https://user-images.githubusercontent.com/68132832/94193474-6611d300-fe7e-11ea-8afe-7517395742bb.png)
(Yes I know that's a redguard but he also has a black face bug.)

**Castle Dour (Solitude):**
![enb2020_9_24_15_48_29](https://user-images.githubusercontent.com/68132832/94193655-9b1e2580-fe7e-11ea-915c-0819229b1b8a.png)

**Dragonsreach **(Whiterun):**
![enb2020_9_24_15_49_25](https://user-images.githubusercontent.com/68132832/94193725-b25d1300-fe7e-11ea-96ba-90f78a5af73a.png)
![enb2020_9_24_15_49_39](https://user-images.githubusercontent.com/68132832/94193732-b5580380-fe7e-11ea-9dbe-1bf42e620543.png)


**Plus a missing texture in **Dragonsreach:****
![enb2020_9_24_15_49_59](https://user-images.githubusercontent.com/68132832/94193767-c143c580-fe7e-11ea-8e1c-12ec0c477742.png)



![enb2020_9_24_15_50_01](https://user-images.githubusercontent.com/68132832/94193781-ca349700-fe7e-11ea-95a6-ecd511ed53df.png)

**Comment by jdsmith2816** [comment]
Fixed in 1.3
