### ISSUE TITLE
Racemenu

### ISSUE THREAD

**Issue by Cygnall** [jdsmith2816/eldersouls#17]
**Describe the bug**
RaceMenu refuses to save changes to advanced values. As in, the changes to minute details often found in the latter half of the slider menus. Any changes to these values are lost upon closing and reopening the game.

**To Reproduce**

1. Make changes to a value, such as "Nose Length 2"
2. Save character.
3. Save the game.
4. Close the game.
5. Reopen the game, no changes to these values were saved.

**Expected behavior**
The values normally should save, but for some reason aren't.

**Screenshots**
https://cdn.discordapp.com/attachments/704708621732151547/705147889197908077/unknown.png
https://cdn.discordapp.com/attachments/704708621732151547/705148272699900015/unknown.png

**Modlist version**
1.0.1

**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment]
Fixed in 1.0.3
