### ISSUE TITLE
Crossbow is missing reloading sound

### ISSUE THREAD

**Issue by darkpeep** [jdsmith2816/eldersouls#170]
**Describe the bug**
When reloading the crossbow, there is no sound to accompany it.

**To Reproduce**

1. Shoot a crossbow
2. Let it reload

3: No sound will play.

**Expected behavior**
For there to be sound when reloading.

**Modlist version**
Newest version as of 9/20/2020
**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment]
Fixed in 1.3
