### ISSUE TITLE
Unspendable Perk Points

### ISSUE THREAD

**Issue by catdevil1234** [jdsmith2816/eldersouls#172]
**Describe the bug**
Using the skyshards mod, I collected 3 skyshards and was rewarded with an additional skill point. However, after sleeping and leveling up skills it does not give me the "spend a perk point" screen it just jumps me right back into the game. I leveled up my skills until i gained an additional level, but it still only let me spend one perk point and still has not given me the option to spend that perk point

**To Reproduce**
1. Find 3 skyshards somewhere in the map and obtain the perk point(They're difficult to find and they can be found indoors, a majority of them are seemingly outdoors though. Theres 6 located in each of the major regions)
2. Sleep in a bed.

**Expected behavior**
After sleeping in a bed, it usually gives you the option to spend a perk point, however it does not. Even if you leveled up, it only gives you the option to spend one perk point at a time

**Modlist version**
I'm pretty inexperienced I couldn't tell you the modlist version, but it was installed on 8/21 from wabbajack (any help on how to do that would be great)
**Did you add any additional mods?**
Nah

**Comment by jdsmith2816** [comment]
Fixed in 1.3
