### ISSUE TITLE
Some mod version not exist anymore

### ISSUE THREAD

**Issue by Marinos33** [jdsmith2816/eldersouls#173]
The following mods don't exist anymore :

- Dwemer Spectres EBT No Blood Patch And Other Fixes-26954-1-3-1589822027 
- Embers HD-14368-1-3998-1591687005
- Northern Cathedral Grass-28706-1-81-1583981350

Please update the mod list with the latest version of them.

**Comment by lexcia98** [comment]
Fixed in previous update.
