### ISSUE TITLE
(New) Black Face Bug : List

### ISSUE THREAD

**Issue by darkpeep** [jdsmith2816/eldersouls#174]
**Describe the bug**
Black Face Bugs

**Expected behavior**
No BFB

**Screenshots**
General Tullius:
![enb2020_9_28_11_20_54](https://user-images.githubusercontent.com/68132832/94458048-66161980-0183-11eb-9c4b-41c796dd8e26.png)

Jarl Ulfric Stormcloak:
![enb2020_9_28_11_14_01](https://user-images.githubusercontent.com/68132832/94458084-71694500-0183-11eb-82be-373dd0c0deff.png)

Irileth
![enb2020_9_28_11_21_37](https://user-images.githubusercontent.com/68132832/94458104-7928e980-0183-11eb-9be3-ae0c961e0fca.png)

Athis:
![enb2020_9_28_12_02_03](https://user-images.githubusercontent.com/68132832/94458147-8ba32300-0183-11eb-923c-ff75bd93b7de.png)

Lord Harkon:
![enb2020_9_28_11_29_07](https://user-images.githubusercontent.com/68132832/94458204-a1b0e380-0183-11eb-9cc7-ae456c873717.png)

Orthjolf:
![enb2020_9_28_11_29_15](https://user-images.githubusercontent.com/68132832/94458282-ba20fe00-0183-11eb-8179-c38bd7c38ce1.png)

Vingalmo:
![enb2020_9_28_11_29_30](https://user-images.githubusercontent.com/68132832/94458310-c6a55680-0183-11eb-817e-07bfae439174.png)

Valerica:
![enb2020_9_28_12_16_32](https://user-images.githubusercontent.com/68132832/94458825-7d093b80-0184-11eb-8485-93f4abdf2aab.png)

Astrid:
![enb2020_9_28_12_18_27](https://user-images.githubusercontent.com/68132832/94459040-ce192f80-0184-11eb-8c10-e388718d0c3f.png)

**Modlist version**
1.2.1.4
**Did you add any additional mods?**
Nope

**Comment by lexcia98** [comment]
Fixed numerous such issues in last update.
