### ISSUE TITLE
Installation Failed - missing mod.

### ISSUE THREAD

**Issue by AzOSRS** [jdsmith2816/eldersouls#175]
**Describe the bug**
Current list of mods is broken by (DMC) The Ultimate Dodge Mod Reanimated.
https://www.reddit.com/r/skyrimmods/comments/jkxigq/you_decide_what_happens_next_subreddit/
The mod page is also gone on nexusmods, explanation above.

**To Reproduce**
Install through Wabbajack and wait until error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/6928075/97788250-f2b75b80-1bb7-11eb-8d63-90e64f88a59f.png)

**Modlist version**
1.1.13

**Did you add any additional mods?**

**Comment by lexcia98** [comment]
Link is in the pins on Discord 
https://drive.google.com/file/d/1rEhTXOxl7JWtELqboNlGcnU6b8OUYyGB/view?usp=sharing
Will be fixed next update.
