### ISSUE TITLE
The mod pack keeps failing to download

### ISSUE THREAD

**Issue by drzoidberg214** [jdsmith2816/eldersouls#176]
**Describe the bug**
The reason why I can not download it is because the mod DMC The ultimate dodge mod reanimated got removed from nexus so it can't download this one mod.

**Modlist version**

**Did you add any additional mods?**

**Comment by lexcia98** [comment]
https://drive.google.com/file/d/1rEhTXOxl7JWtELqboNlGcnU6b8OUYyGB/view?usp=sharing

Known issue. Being fixed. Place file linked in download folder
