### ISSUE TITLE
Change the player knockdown from pounce attacks to a stagger.

### ISSUE THREAD

**Issue by SerDagron** [jdsmith2816/eldersouls#177]
**Request**
If the knockdown effect from pounce attacks by Wolves/Sabre Cat's/Death Hounds etc. could be changed to a stagger.

**Additional context**
Requesting this mainly because the stand up animation is too slow (even with the "faster get up" animations installed). If a Sabre Cat or Dragon knocks me down they usually kill me before I can stand up (less so with the faster animations but it still happens). If it's a pack of Wolves or Death Hounds, I end up being stun-locked because they will repeatedly use the pounce attack to keep me on the floor.

I'm all for making the game harder, but being killed because you can't stand up just feels like a cheap death.

**Comment by jdsmith2816** [comment]
Fixed in 1.3.1
