### ISSUE TITLE
Modlist down due to Glenmoril upgrade

### ISSUE THREAD

**Issue by Ellimist000** [jdsmith2816/eldersouls#181]
According to Wabbajack, the mod that is not passing now is the Glenmoril translation, as Glenmoril has gotten a significant upgrade. The translation is hidden while it is being upgraded. Likely both Glenmoril and the translation will have to be upgraded in the mod list.

**Comment by Ellimist000** [comment]
The previous issue may be resolved, as only the Glenmoril Translation appeared to be failing.

**Comment by jdsmith2816** [comment]
Will be down until i release version 1.3 hopefully by end of year... we'll see.
