### ISSUE TITLE
Starts besides Helgen does not work.

### ISSUE THREAD

**Issue by SovnSkyrim** [jdsmith2816/eldersouls#183]
I tried :
- Camping in the woods
- Vigilant of Stendarr
- I am a soldier in the army.
All 3 does not TP me out of the cell, the screen fades to black normally but I stay in the LAL cell and the statue of Mara disappears.
Vanilla Start works correctly though.

**Comment by SovnSkyrim** [comment]
Seems to be fixed with the reset update

**Comment by jdsmith2816** [comment]
Great.
