### ISSUE TITLE
Missing Texture Thread

### ISSUE THREAD

**Issue by SovnSkyrim** [jdsmith2816/eldersouls#184]
Refined Iron Armor
http://prntscr.com/w6irjd

Base Form: 8501a853
Ref Form ff001ba9
Origin: aMidianborn_ContentAddon.esp
http://prntscr.com/w6isaz

**Comment by SovnSkyrim** [comment]
Iron Armor
http://prntscr.com/w6jpvj

Base form 8506F983
Ref Form FF001C04
Origin: aMidianBorn_ContentAddon.esp

**Comment by SovnSkyrim** [comment]
Arrow Target
http://prntscr.com/w6o6x1

Base form 66af6
Ref form c1db2
Origin: Skyrim.esm

**Comment by SovnSkyrim** [comment]
Refined Banded Iron Armor
http://prntscr.com/w6pr0s

Base Form 8501a857
Ref Form ff001cb7
Origin: aMidianBorn_ContentAddon.esp

**Comment by jdsmith2816** [comment]
Fixed the above
