### ISSUE TITLE
From Ominous to Apex Somber + ReShade Addition

### ISSUE THREAD

**Issue by SovnSkyrim** [jdsmith2816/eldersouls#185]
I absolutely love Ominous and is an absolute wonderful ENB, but I think Apex Somber is much better in the grim category of ENBs.
Here's a link: https://www.nexusmods.com/skyrimspecialedition/mods/41598?tab=description
video showcase https://youtu.be/td9aCcgB-gw (on Elder Souls!)

Also, If you're willing to modify a bit your ReadMe for lower end pc users, it'd be nice a little word on Ulver ReShade (https://www.nexusmods.com/skyrimspecialedition/mods/40433) which is much more fps friendly than an ENB but still makes it grim and fitting the souls theme.

**Comment by jdsmith2816** [comment]
Agreed on the swap to Apex; this is done now.

Feel free to open a PR with updates to the readme about Ulver ;)
