### ISSUE TITLE
CTDs Thread

### ISSUE THREAD

**Issue by SovnSkyrim** [jdsmith2816/eldersouls#186]
[Crash_2020_12_20_14-53-24.txt](https://github.com/jdsmith2816/eldersouls/files/5721001/Crash_2020_12_20_14-53-24.txt)

Here's the crashlog. as soon as I approach the end of the forest towards Whiterun from Riverwood.
This has been tried 4times
Yes it's a memory crash, I have a good pagefile and my GPU Drivers are updated.

**Comment by SovnSkyrim** [comment]
A "coc whiterun" does not make me crash though.

**Comment by SovnSkyrim** [comment]
[Crash_2020_12_20_15-55-9.txt](https://github.com/jdsmith2816/eldersouls/files/5721075/Crash_2020_12_20_15-55-9.txt)

New Crash, this time alongside Lake Ilinalta, approaching the Standing Stone that is in the lake.

I'm starting to think this is a problem with my computer as it's another Memory Crash.

**Comment by SovnSkyrim** [comment]
Seems to be caused by Reyliik do Skyrim, corrupted DDs

**Comment by SovnSkyrim** [comment]
[Crash_2020_12_20_18-7-8.txt](https://github.com/jdsmith2816/eldersouls/files/5721229/Crash_2020_12_20_18-7-8.txt)

New crash fighting goblins.
Latest VC is installed so I do not know about those skeleton.nif stuff.

**Comment by SovnSkyrim** [comment]
[Crash_2020_12_20_19-42-39.txt](https://github.com/jdsmith2816/eldersouls/files/5721334/Crash_2020_12_20_19-42-39.txt)
[Crash_2020_12_20_19-44-49.txt](https://github.com/jdsmith2816/eldersouls/files/5721335/Crash_2020_12_20_19-44-49.txt)

New Crash, Loading a Savefile, saved right before a fight with goblins and a Minotaur on my way to Falkreath. (road close to Auri's Pod) 
All crashes during loads are from using the scroll (Full saves) I can load quick saves just fine.

**Comment by SovnSkyrim** [comment]
[Crash_2020_12_20_22-18-14.txt](https://github.com/jdsmith2816/eldersouls/files/5721531/Crash_2020_12_20_22-18-14.txt)
[Crash_2020_12_20_22-16-17.txt](https://github.com/jdsmith2816/eldersouls/files/5721532/Crash_2020_12_20_22-16-17.txt)

New Crash, loading a savefile, saved right before the fight with Vals Veran and the ugly thing in it's dungeon (Hillgrund's Tomb).

**Comment by SovnSkyrim** [comment]
[Crash_2020_12_21_19-37-29.txt](https://github.com/jdsmith2816/eldersouls/files/5725911/Crash_2020_12_21_19-37-29.txt)

New Crash, loading a savefile, savec on the bridge towards the College of Winterhold.
 I actually had an infinite loading screen right before, from the college worldcell to the hall of attainment's cell.

**Comment by jdsmith2816** [comment]
Unable to reproduce on latest build
