### ISSUE TITLE
BlackFace Thread

### ISSUE THREAD

**Issue by SovnSkyrim** [jdsmith2816/eldersouls#188]
Fralia Gray-Mane
http://prntscr.com/w6psyi
Base Form 13b9c
Ref Form 1a684

**Comment by SovnSkyrim** [comment]
I'm gonna check Fralia again as I've updated but,
Vigilant of Stendarr 
0010c484/000f9626 from Skyrim.esm has a blackface

**Comment by SovnSkyrim** [comment]
Guard from Diverse Skyrim
2B066D92
00057697

**Comment by SovnSkyrim** [comment]
Jarl Skald 13620/1a6c0
Brina Merilis 1a6b7/1a6b8

**Comment by jdsmith2816** [comment]
These seem to be fixed now... That was a whoooooole thing.

**Comment by SovnSkyrim** [comment]
Jarl Korir
1c188/1c1b5
From Skyrim ESM

**Comment by SovnSkyrim** [comment]
Ancano
1e7d7/1e7d8

http://prntscr.com/w814nf

**Comment by jdsmith2816** [comment]
resolved

**Comment by SovnSkyrim** [comment]
Tolfdir 
1c19e/1c1a1
http://prntscr.com/w8jww0

**Comment by SovnSkyrim** [comment]
Drevis Neloren
1c198/1c1a6

http://prntscr.com/w8k398

**Comment by jdsmith2816** [comment]
resolved
