### ISSUE TITLE
Infinite Loading Screen Thread

### ISSUE THREAD

**Issue by SovnSkyrim** [jdsmith2816/eldersouls#191]
The Hall of Attainment cannot be loaded from the main entrance in the College of Winterhold courtyard, it's repeatable.
Since it's an ILS, no crashlog appears.

**Comment by jdsmith2816** [comment]
Cannot seem to reproduce

**Comment by SovnSkyrim** [comment]
It seems to appear only when Mirabelle Ervine is giving you the tour of the College

**Comment by jdsmith2816** [comment]
Closing due to inability to reproduce on current build.
