### ISSUE TITLE
Blackface bug on Danica Pure-Spring

### ISSUE THREAD

**Issue by mysticfire007** [jdsmith2816/eldersouls#199]
**Describe the bug**
Danica Pure-Spring has a blackface

**To Reproduce**
Go to Whiterun and see her xD

**Expected behavior**
No Black face
**Screenshots**
![image](https://user-images.githubusercontent.com/76411123/104134242-b018b900-5388-11eb-9750-35190a0ac254.png)

**Modlist version**
1.4
**Did you add any additional mods?**
No

**Comment by ianitm** [comment]
Same as well as some bandits and some of the companions.

**Comment by jdsmith2816** [comment]
Fixed in ESv1.5
