### ISSUE TITLE
Black Face Bug

### ISSUE THREAD

**Issue by gold-n-exp** [jdsmith2816/eldersouls#202]
**Describe the bug**
Infamous black face bug on certain npcs

**To Reproduce**
Not sure how many npcs are affected, so far seen on Danica and Ulfberth

![bug](https://user-images.githubusercontent.com/77557618/104828253-d7f69980-582c-11eb-87e6-7706164293c0.jpg)

**Modlist version**
uhh not sure but its the latest one

**Did you add any additional mods?**
no

**Comment by ianitm** [comment]
I have the issue, same NPCs. It affected some bandits as well and some of the companions.

**Comment by jdsmith2816** [comment]
Fixed in ESv1.5
