### ISSUE TITLE
Unable to download enbseries_skyrimse_v0452.zip (HTTPDownloader+state| http://enbdev.com/enbseries_skyrimse_v0452.zip)

### ISSUE THREAD

**Issue by poisonkp** [jdsmith2816/eldersouls#204]
I cant proceed with the download

as the title suggest.

Keep up the good work :)
![image](https://user-images.githubusercontent.com/80549342/110999902-c55e9380-8389-11eb-98d0-a6f5a3cbc76a.png)

**Comment by Indexu** [comment]
Also experiencing this.
Even tried to download the file manually and placing it in the downloads directory. Error about incorrect hash and proceeds to fail to download the file as before.
![image](https://user-images.githubusercontent.com/5814332/111052631-6c0f6680-8454-11eb-89a2-7e4fc6e6951c.png)

**Comment by PekoDwell** [comment]
I'm having the same problem as well.
[Wabbajack.current.log](https://github.com/jdsmith2816/eldersouls/files/6175623/Wabbajack.current.log)

**Comment by Zvarrit** [comment]
There is a way to resolve this issue : download enbseries v0452, then remove the "Linux" folder in the zip. There was a update to the file, so the hash didn't work anymore. But removing this folder make it work.
