### ISSUE TITLE
Unable to download DS3 Weapon Pack

### ISSUE THREAD

**Issue by Zvarrit** [jdsmith2816/eldersouls#209]
**Describe the bug**
When Wabbajack send you download the DS3 Weapon Pack, nothing happen when you try to download it. I'm connected to LoversLab. 
When I try to download the mod manually and put it in the download folder of Wabbajack, nothing happen, and it ask to download it again.
And the link to download the pack in the description of the modlist don't work.

**To Reproduce**

1. Try to install the modlist with Wabbajack

**Expected behavior**
Download the file, or giving the version needed ?

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**
1.5

**Did you add any additional mods?**
No

**Comment by Ahsome** [comment]
I tried this today, and I received the same issue as well. Even when I downloaded the file externally and kept it in the "downloads" folder

**Comment by Zvarrit** [comment]
Ok, I find a solution : you must download the 1.13 version of the mod in version LE.

**Comment by Ahsome** [comment]
What else did you do after that? Did you download 1.13 from the Wabbajack browser, or separately and placed in the downloads folder?
