### ISSUE TITLE
Floating tree at Old Hroldan Inn

### ISSUE THREAD

**Issue by lexcia98** [jdsmith2816/eldersouls#21]
**Describe the bug**
A floating tree
**To Reproduce**
Go to where the tree is. 

**Expected behavior**
You see a floating tree

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.
![20200430_125146](https://user-images.githubusercontent.com/64607591/80743265-4e5a3c80-8ae2-11ea-8fd8-b89c1ab44895.jpg)

**Modlist version**
Latest as of April 29th.
**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment]
Fixed in 1.0.2
