### ISSUE TITLE
Unable to download modlist after one or more archive failed

### ISSUE THREAD

**Issue by Freeeli** [jdsmith2816/eldersouls#213]
Windhelm HD Retextured failed to download along with a file named Kart and now I'm getting a modlist error

After the last 2 mods were installing (Windhelm HD Retextured and Kart) and they failed to download.
I then exited like the guide said and tried to continue where I left off and I'm getting a modlist failed to download error.
I've tried multiple times now and I keep getting the same error

here is the error from the origional installtion process

[Wabbajack 2021-04-19 18_16_31 copy.txt](https://github.com/jdsmith2816/eldersouls/files/6339606/Wabbajack.2021-04-19.18_16_31.copy.txt)

**Comment by Freeeli** [comment]
I'm seeing that they are  both broken. are there any workarounds?? I spent 8 hours on this today and I really dont want it to be for nothing. That being said I know this issue isnt any of the people that curated the lists fault. really appreciate the hard work.

**Comment by kyphius** [comment]
same.. dang all that time dl-ing everything else, i shouldve looked here first.

**Comment by Freeeli** [comment]
well it wouldn't have dont you much good. For some reason wabbajack is giving a greenlight on the status dashbored. It just updated on the 20th I beleive.
