### ISSUE TITLE
Wabbajack: ElderSouls: Unable to download enbseries_skyrimse_v0452.zip

### ISSUE THREAD

**Issue by dschaatsbergen** [jdsmith2816/eldersouls#215]
I'm unable to download enbseries_skyrimse_v0452.zip and the log also says unable to download. 

There is a new version available enbseries_skyrimse_v0454zip, the old version is not there anymore and installation failed because of this.

current versions of the modlist downloaded today 2 May 2021

**Comment by lexcia98** [comment]
List .wabbajack file updated like a week ago, sorry I didn't respond. Just download the new one and it should work.

**Comment by dschaatsbergen** [comment]
No need to say sorry, I'm happy you fixed it.
Thanks a lot.
