### ISSUE TITLE
Gameplay-only version?

### ISSUE THREAD

**Issue by shazdeh** [jdsmith2816/eldersouls#23]
Very excited about this modlist, however with all the texture packs and npc overhauls and stuff, the size is a bit much, both in terms of bandwidth and disk space. Was wondering if you'd consider a gameplay-only version of this, where it only includes mods related to gameplay. This could have several benefits:
 - one being for people who want to give this a try to see how it is, they can do so much easier and faster.
 - two, if you want to customize the modlist later on, it'd be easier as well.

Thank you!

**Comment by jdsmith2816** [comment]
Thanks for the kind words but I won't be making alternate versions of the modlist.  I wish you the best of luck in finding something that meets your needs.
