### ISSUE TITLE
Death waypoint

### ISSUE THREAD

**Issue by lexcia98** [jdsmith2816/eldersouls#24]
**Request**
Way to track general location of death in order to ease tracking down gravestone.

**Additional context**
Skyrim is huge and trying to track down a specific spot in the wilderness results in a greater challenge when recovering souls outside dungeons as compared to Souls games.

**Comment by jdsmith2816** [comment]
Agreed.  I plan to do this soon.

**Comment by jdsmith2816** [comment]
This is fixed in 1.0.4 as the gravemarker now has a giant beacon attached to it.

![Uploading image.png…]()
