### ISSUE TITLE
Grant level up on gaining dragon soul

### ISSUE THREAD

**Issue by Monica-21** [jdsmith2816/eldersouls#25]
**Request**
Add a feature that grants a level up on gaining a dragon soul.

**Additional context**
I'm not at all sure how well this would be balanced and also not sure how this would affect players who didn't play as the Dragonborn. However, in a game that, in its vanilla state, is heavily tied to the player character absorbing dragon souls, it seems a logical step that a dragon would then become the ultimate boss soul.

**Comment by jdsmith2816** [comment]
While this idea is interesting I think I have other plans for dragon souls. Thanks for the suggestion though!
