### ISSUE TITLE
Jarl Elisif Chambers Bug

### ISSUE THREAD

**Issue by Cygnall** [jdsmith2816/eldersouls#27]
**Describe the bug**
If you speak to Jarl Elisif in the Blue Palace, she'll ask you to meet her in her chambers at night if you click a specific option.

**To Reproduce**

1. Go to 'the Blue Palace' in Solitude
2. Speak to Jarl Elisif
3. One of her options is about speaking to her about something, it's the last/ second-to-last option she has on a new playthrough. (Can't get exact text, can't load a save lol)
4. She'll tell you to meet her in her chambers at night, Quest listed in Misc. section, screenshotted below
5. When entering her chambers, she'll proclaim that you're not supposed to be there and call the guards.

**Expected behavior**
She should probably have something to say, ha

**Screenshots**
https://i.imgur.com/dM9IhBp.png

**Modlist version**
1.0.2

**Did you add any additional mods?**
No

**Comment by lexcia98** [comment]
Finish the quest The Wolf Queen Awakened to stop being considered a trespasser in her chambers so you can proceed with that quest. Closing old issues. Will see if possible to delay her asking you to her chambers till after The Wolf Queen Awakened is completed.
