### ISSUE TITLE
Aesthetics, Visuals, Trees, Assets, Sounds - Bugs

### ISSUE THREAD

**Issue by Cygnall** [jdsmith2816/eldersouls#28]
**Describe the bug**
This is a masterlist for all the visual bugs I find. Hope it helps!

**Screenshots**
In the woods along the coast near Solitude.
![image](https://user-images.githubusercontent.com/31330700/80895583-8dd88280-8cb4-11ea-8d36-ebf291ba8723.png)

Water reflections artefacting a bit, lines segmenting the reflection
![image](https://user-images.githubusercontent.com/31330700/80895733-0855d200-8cb6-11ea-8824-b031e3dacfb2.png)

Level/ Level Bar a little off-centered.
![image](https://user-images.githubusercontent.com/31330700/80896550-70f47d00-8cbd-11ea-9e65-7cf5014e7dc4.png)

Statue on a pillar in Dragon's Bridge. Weird lines on the texture.
![image](https://user-images.githubusercontent.com/31330700/80910640-f2b8ca80-8cfe-11ea-9e59-35bde87e0b42.png)

Pretty sure there's supposed to be a mesh for a bone hill here. In the Velothi Mountain Tunnels third cell.
![image](https://user-images.githubusercontent.com/31330700/80913821-8b5a4500-8d15-11ea-845a-0693b3d5cf1d.png)

Texture missing in the Clockwork Castle Grounds.
![image](https://user-images.githubusercontent.com/31330700/80921893-5535b900-8d47-11ea-9933-056cd4cc9fa0.png)

When stepping through this type of Dwemer door, or really any Dwemer door I've found, The bass gets really crackly and poorly mixed.
![image](https://user-images.githubusercontent.com/31330700/80921863-11db4a80-8d47-11ea-9b69-f3f0cca585d4.png)

Weird Sometimes slow animations and mismatching of timing
Using a Forge, you can see the player model is moving at a different speed than the forge itself
![image](https://user-images.githubusercontent.com/31330700/80950056-2a894600-8dc3-11ea-894f-510417c2537d.png)
Turning a page in a book is painstakingly slow, but only when reading books from the ground. Books from the inventory are fine.
![image](https://user-images.githubusercontent.com/31330700/80950339-a71c2480-8dc3-11ea-94e6-62133a0aac54.png)

Opening the console mid-animation for either seems to fix the majority of the sluggishness.

Evidence of fixed timing by opening console at the beginning of the animation.
![image](https://user-images.githubusercontent.com/31330700/80950491-f6625500-8dc3-11ea-8f14-682a6cd9f544.png)

Floating tree in Darkend
![image](https://user-images.githubusercontent.com/31330700/81034685-f4e96900-8e65-11ea-8e72-98b9d9cf3e4b.png)

Missing texture near Ancient Bridge in Darkend
![image](https://user-images.githubusercontent.com/31330700/81034706-0b8fc000-8e66-11ea-8a00-ff118abe69b3.png)

Another floating tree in Darkend
![image](https://user-images.githubusercontent.com/31330700/81062439-f46fc300-8ea3-11ea-820d-b749937a17f7.png)

**Comment by Cygnall** [comment]
When stepping through this type of Dwemer door, or really any Dwemer door I've found, The bass gets really crackly and poorly mixed.
![image](https://user-images.githubusercontent.com/31330700/80921863-11db4a80-8d47-11ea-9b69-f3f0cca585d4.png)

**Comment by jdsmith2816** [comment]
All remaining issues addressed for 1.1.4
