### ISSUE TITLE
Switch from UNP to CBBE

### ISSUE THREAD

**Issue by Cygnall** [jdsmith2816/eldersouls#29]
**Request**
I think it'd be a good idea to switch to CBBE, as it makes the Practical Female Armors mod way more functional, since it comes with CBBE Morphs as an optional download. Also... I just kinda prefer it to UNP, ha.

**Additional context**
Not a fan of UNP
![image](https://user-images.githubusercontent.com/31330700/80895630-f0318300-8cb4-11ea-9f46-8a45a213a1c0.png)

**Comment by jdsmith2816** [comment]
After reviewing things I think we need to stick with UNP as the official body mod as the various Soulsborne armor sets that I plan to add mostly seem to be vanilla and UNP based.

**Comment by Cygnall** [comment]
For whenever this re-opens

Here's the link to CBBE SSE
https://www.nexusmods.com/skyrim/mods/2666?tab=description

Practical Female Armors has those CBBE Morph Files, don't forget
https://www.nexusmods.com/skyrimspecialedition/mods/2628/?tab=files&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fskyrimspecialedition%2Fajax%2Fmodimages%2F%3Fuser%3D0%26id%3D2628%26gid%3D1704

And here's the best texture set I know of for CBBE, it's very good.
https://www.nexusmods.com/skyrimspecialedition/mods/20078?tab=description

**Comment by jdsmith2816** [comment]
Done for 1.0.3
