### ISSUE TITLE
Haunted Penitus Oculatus

### ISSUE THREAD

**Issue by langevonschwerin** [jdsmith2816/eldersouls#30]
**Describe the bug**
Sounds of the undead and other horrible noises are permeating the space. Leaving the building and walking around Dragon Bridge finds no such noises.

**To Reproduce**

1. Go to 'Penitus Oculatus outpost. I chose the Alternate Start that spawns you there.'
2. Do 'nothing. Sounds are very loud.'

**Expected behavior**

No screaming, squelching, moaning, skittering, or vomiting noises.

**Screenshots**
No screenshots available.

**Modlist version**

v1.0.2

**Did you add any additional mods?**

Only simple lock-on, but this happened in 1.0.1 as well; I never made additions then..

**Comment by jdsmith2816** [comment]
Fixed in 1.3
