### ISSUE TITLE
Inigo Arrows Crash

### ISSUE THREAD

**Issue by Cygnall** [jdsmith2816/eldersouls#31]
**Describe the bug**
Giving Inigo a lot of arrows crashes the game.

**To Reproduce**

1. Go to 'Riften Jail' to meet Inigo the first time
2. Listen to his story, then try to give him at least 400 of the iron arrows from his storage chest.

**Expected behavior**
Inigo gets some arrows with no crash.

**Screenshots**
N/A

**Modlist version**
1.0.2

**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Unable to reproduce in v1.1.3  Feel free to reopen with a crash log if you find a way to reproduce the issue.
