### ISSUE TITLE
Game save option

### ISSUE THREAD

**Issue by ChrisJordan92** [jdsmith2816/eldersouls#32]
When the game starts for the first time, make a popup that lets the player choose how saving in game should work. The choices would as the following:

1. One time save (the current setup)
2. Save anytime

Once this is set, it cannot be changed.

This is so that players have the flexibility to choose if they want to be able to save the game anytime, or stick with the current setup. I'm sure some people are turned off by this feature. This option would allow for more flexibility.

**Comment by jdsmith2816** [comment]
I might end up doing something like this but for now I'm going with the simple idea of giving you an elder scroll every 15m if you don't have one.
