### ISSUE TITLE
Add Beds to Tagged

### ISSUE THREAD

**Issue by Cygnall** [jdsmith2816/eldersouls#33]
**Request**
This is a list of beds I'd like to be respawnable, please!

**Additional context**

First bed I found is in Velothi View Inn.
![image](https://user-images.githubusercontent.com/31330700/80911139-7b853580-8d02-11ea-9dcd-0aa171f8d4c7.png)

Don't know if they are already, but it would be kinda neat if you could tag the beds in Velothi Mountain Tunnels so you can keep to the theme of the mod and not leave the dungeon. Part of the Clockwork Castle mod. There's three beds.
![image](https://user-images.githubusercontent.com/31330700/80912791-7f6a8500-8d0d-11ea-9936-abcb074222fd.png)

Here's a Cot in the Pharros Church of Darkend
![image](https://user-images.githubusercontent.com/31330700/81034548-899f9700-8e65-11ea-9df1-7eee3b0852f7.png)

**Comment by jdsmith2816** [comment]
Leaving open for others to add more.  Above this line incorporated into 1.0.3

**Comment by rshackleton** [comment]
Similar issue, the beds you can build as part of the Millwater Retreat player home don't allow you to respawn there - unless I'm missing something?

**Comment by jdsmith2816** [comment]
@rshackleton If you can get me a console screenshot like the ones above of one of the beds in question then I'll get it fixed for v1.1.11

**Comment by rshackleton** [comment]
This is one of them, you can build three different types though.

![image](https://user-images.githubusercontent.com/13448395/82147283-9bf6d900-9846-11ea-98c5-c2effb2da25e.png)

**Comment by jdsmith2816** [comment]
Thanks.  Type of bed doesn't matter really.  The console screenshot gives me a formid which easily let's me find which cell it's in.. It's the cell that matters.

**Comment by jdsmith2816** [comment]
Beds in millwater retreat are flagged in 1.1.7
