### ISSUE TITLE
Crashing Upon Entering Windhelm (Elder Souls 1.0.2)

### ISSUE THREAD

**Issue by HollerHavoc** [jdsmith2816/eldersouls#34]
**Describe the bug**
If it's relevant, I have a fresh install with the latest github version of simplelockon installed. On a fresh character I chose to start by escaping the prison after following the mcm guide for follower framework. I escaped the prison and headed for Windhelm. Upon trying to enter the gate my game hard crashed. I reloaded a save I made nearby and managed to get into the place no problem but upon trying to enter the inn right near the entrance it crashed again.

**To Reproduce**
1: Make a fresh character
2: Choose escape from this prison option
3: Escape the prison and head to Windhelm
4: See if it crashes when entering it
5: If it doesn't crash try entering the Inn and see if it does

**Expected behavior**
I expected to be able to enter Windhelm

**Screenshots**

**Modlist version**
1.0.2

**Did you add any additional mods?**
SimpleLockon (Latest Github Version)
[Crash_2020_5_3_20-48-23.txt](https://github.com/jdsmith2816/eldersouls/files/4572429/Crash_2020_5_3_20-48-23.txt)
[Crash_2020_5_3_20-13-8.txt](https://github.com/jdsmith2816/eldersouls/files/4572430/Crash_2020_5_3_20-13-8.txt)

**Comment by jdsmith2816** [comment]
Unable to reproduce in v1.1.4 following the steps outlined above.  Feel free to re-open this with a new crashlog if you are able to make it happen again in the current version.
