### ISSUE TITLE
Old Windmill Inn Untextured

### ISSUE THREAD

**Issue by Brant20154** [jdsmith2816/eldersouls#35]
**Describe the bug**
The Old Windmill Inn is Untextured

**Screenshots**
![ScreenShot6](https://user-images.githubusercontent.com/45091438/80944765-26e3c800-8d9f-11ea-907e-f519135c6436.png)
![ScreenShot7](https://user-images.githubusercontent.com/45091438/80944773-2814f500-8d9f-11ea-8bd6-b95f275dd172.png)

**Modlist version**
1.0.2
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Resolved in 1.0.3
