### ISSUE TITLE
Lock pick breaking adds skill xp

### ISSUE THREAD

**Issue by ThrasherGX** [jdsmith2816/eldersouls#37]
**Describe the bug**
Breaking lockpicks still gives a small amount of progress toward the next skill level.

**To Reproduce**

1. Attempt to pick a lock.
2. Break a lockpick
3. Progress bar will advance a small amount.

**Expected behavior**
Skill progress should not occur when breaking lockpicks

**Modlist version**
1.0.3
**Did you add any additional mods?**
Simple Lock-On

**Comment by jdsmith2816** [comment]
Fixed in 1.0.4
