### ISSUE TITLE
Tilma the Haggard - NPC with no body

### ISSUE THREAD

**Issue by RedAxon** [jdsmith2816/eldersouls#38]
**Describe the bug**
Tilma the Haggard (cleaner/maid at Jorrvaskr) doesnt have a body, just a floating head. 

**To Reproduce**

1. Go to 'Jorrvaskr' and find Tilma

**Screenshots**

![enb2020_5_6_16_40_58](https://user-images.githubusercontent.com/64914492/81198099-00997480-8fb9-11ea-95e1-328ca3e7d938.jpg)

**Modlist version**

1.0.3

**Did you add any additional mods?**

Simple lock on, utilising the link provided by the mod list creator.

**Comment by rshackleton** [comment]
Same issue, no additional mods and modlist v1.1.1.

**Comment by jdsmith2816** [comment]
This was fixed in v1.1.8
