### ISSUE TITLE
Weapons, armor, and magic skill level requirements

### ISSUE THREAD

**Issue by crackafoo** [jdsmith2816/eldersouls#39]
Not sure if this is part of your vision for Elder Souls, but I think some kind of requirements for weapons, armors, and spells would add to the gameplay. 
Something like "TDF Equipment Restriction" for example.
https://www.nexusmods.com/skyrimspecialedition/mods/22830
Just wanted to throw the idea out there, I like requirements. It makes me look forward to continue playing and be able to use some sweet weapon or spell I found but I'm unable to use yet. 
And it also increases the amount of weapons I end up trying out because I can't just use the "top damage" one yet.

**Comment by jdsmith2816** [comment]
Thanks.  I like this idea and will consider it.

**Comment by jdsmith2816** [comment]
I've considered this more and I think I want a system in place but I think YASH has the superior requirements system.  TDF Equipment Restriction only applies to players... YASH's system applies to both players and NPCs.  I will see if it's possible to pull the requirement system out of YASH and use it stand alone for elder souls.

**Comment by crackafoo** [comment]
Awesome! I hope that goes well. Totally I agree, YASH does it better.  I mentioned TDF just cause it did the only thing I was talking about. Thought it would make what I was trying to say more clear lol

**Comment by jdsmith2816** [comment]
I was lazy and just added TDF.
