### ISSUE TITLE
Farengar's Orb Causes Framerate Drop

### ISSUE THREAD

**Issue by ThrasherGX** [jdsmith2816/eldersouls#40]
**Describe the bug**
When looking at the crystal orb on Farengar's desk in whiterun, framerate drops incredibly low.
(I go from about 50fps to slide show mode)

**To Reproduce**

1. Look at the orb on Farengar's desk.
2. Framerate plummets.

**Expected behavior**
Framerate should not drop so much just from looking at an object.

**Screenshots**
![enb2020_5_6_20_22_49](https://user-images.githubusercontent.com/38668000/81244249-7b718800-8fd7-11ea-8b78-a1ee03479aef.png)

**Modlist version**
1.0.3
**Did you add any additional mods?**
Simple Lock-On

**Comment by jdsmith2816** [comment]
Fixed in 1.1.4
