### ISSUE TITLE
Crash when equipping poisoned crossbow

### ISSUE THREAD

**Issue by Squatchyfz** [jdsmith2816/eldersouls#41]
**Describe the bug**
Immediate CTD upon unsheathing a crossbow outside Bleak Falls Barrow after poisoning it.

**To Reproduce**
Unable to reliably reproduce

**Expected behavior**
I equipped the crossbow, then applied poison and when I pressed the button to bring out the crossbow the game crashed. with no error or anything.

**Modlist version**
Newest, installed today.

**Did you add any additional mods?**
None.

**Comment by jdsmith2816** [comment]
Unable to reproduce in 1.1.3.  Feel free to re-open with a crashlog if you can still reproduce it.
