### ISSUE TITLE
Visible Activator in Morthal

### ISSUE THREAD

**Issue by ThrasherGX** [jdsmith2816/eldersouls#42]
**Describe the bug**
Visible Activator object.

**To Reproduce**

1. Morthal
2. Talk to Igrid to start the quest Laid To Rest
3. Go to the burned house in morthal during the day.  Make sure this is the first time you have gone.
4. In the center of the burned house is a red X marker

**Expected behavior**
Activators and other Triggers should not be visible.

**Screenshots**
![enb2020_5_7_19_40_45](https://user-images.githubusercontent.com/38668000/81358076-15e6cf80-909b-11ea-9c59-88f7a5d8dfb1.png)

**Modlist version**
1.0.3
**Did you add any additional mods?**

**Comment by jdsmith2816** [comment]
This will be resolved in 1.1.8 with the rebuilt ECTV mod.
