### ISSUE TITLE
CTD upon entering Whiterun

### ISSUE THREAD

**Issue by Squatchyfz** [jdsmith2816/eldersouls#43]
**Describe the bug**
Crash upon activating main door to Whiterun. (during loading screen.)

**To Reproduce**
Open main door to Whiterun. 

**Expected behavior**
Game may crash upon loading.

**Screenshots**

**Modlist version**
Newest

**Did you add any additional mods?**
No.

[Crash_2020_5_7_17-53-35.txt](https://github.com/jdsmith2816/eldersouls/files/4596504/Crash_2020_5_7_17-53-35.txt)

**Comment by jdsmith2816** [comment]
Fixed in 1.0.4
