### ISSUE TITLE
Adding SKYTWEAK

### ISSUE THREAD

**Issue by padamphet** [jdsmith2816/eldersouls#44]
Hi There !
I would like to know if it is possible to add skytweak in the modlist . Because it can just help to tweak combat things ( damage dealt and taken, for exemple), experience (if you want slower or faster levelling) and it is very good when you reach high level and feel godlike, you can make the game harder. Of course, it is possible to add a menu in MCM menu and explain what should not be touched and what is allowed to be tweaked to not corrupt the vision of the game you have :) 
I hope you understand my English  :)  :)

**Comment by jdsmith2816** [comment]
This is something you should just add on your own;  there should be no conflicts to worry about.  Just install it at the bottom and leave it where it ends up
