### ISSUE TITLE
DCR King Crusader Armor

### ISSUE THREAD

**Issue by Squatchyfz** [jdsmith2816/eldersouls#46]
**Request**
I think this armor would fit well within the mod list.

**Additional context**
https://www.nexusmods.com/skyrimspecialedition/mods/8856

![82543-11-1488628312 1](https://user-images.githubusercontent.com/64945135/81460545-eeefd280-915a-11ea-9d33-c7afff9ad527.jpg)

**Comment by jdsmith2816** [comment]
Added in 1.0.4
