### ISSUE TITLE
Tilma The Haggard Invisible Hands

### ISSUE THREAD

**Issue by Raiuki** [jdsmith2816/eldersouls#47]
**Describe the bug**
Tilma The Haggard has invisible hands shes wearing Common Clothes Ref ID 0006C1D9

**To Reproduce**

1. Go to 'Jorrvaskr'
2. Do 'find Tilma'

**Expected behavior**

**Screenshots**
https://cdn.discordapp.com/attachments/355433345598881792/708647303074021387/ScreenShot1.png

**Modlist version**
1.0.3
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Duplicate of https://github.com/jdsmith2816/eldersouls/issues/38
