### ISSUE TITLE
wabbajack.manifest.json file?

### ISSUE THREAD

**Issue by shazdeh** [jdsmith2816/eldersouls#48]
**Request**
When you download Lotus modlist it comes with a Lotus.wabbajack.manifest.json file, I was wondering whether that's a file generated by Wabbajack and if you could share that as well?

Reason being, the .json file is parsable so I wrote a little php script for myself that checks for existing files within my hard drives and copies them to the `mo2/downloads` so it wouldn't need to be downloaded again. It speeds up the installation time by insane amounts.

Thank you!

**Comment by jdsmith2816** [comment]
It's a file generated by WJ.  I'll try to make sure to include it in the releases going forward.

**Comment by shazdeh** [comment]
Amazing, thank you!
