### ISSUE TITLE
Floating Tree at Incautious Bather grove

### ISSUE THREAD

**Issue by ThrasherGX** [jdsmith2816/eldersouls#49]
**Describe the bug**
A floating tree northeast of Markarth, at the map location called "Incautious Bather"

**To Reproduce**

1. Go to Incautious Bather
2. Near the pool, is a large tree that is floating.

**Expected behavior**
Trees should not float. (Unless they are magic...)

**Screenshots**
![enb2020_5_9_11_05_39](https://user-images.githubusercontent.com/38668000/81478833-610cf980-91e5-11ea-9595-7ce1256dda32.png)

**Modlist version**
1.0.3
**Did you add any additional mods?**
Simple Lock On

**Comment by jdsmith2816** [comment]
Fixed in 1.1.4
