### ISSUE TITLE
Chest in tree

### ISSUE THREAD

**Issue by AFranklin41** [jdsmith2816/eldersouls#5]
**Describe the bug**
A floating chest near Soljund's Sinkhole

**To Reproduce**
Go to Soljund's Sinkhole, up the road a slight bit behind the building

**Expected behavior**
Probably the chest shouldn't be in the tree

**Screenshots**
https://i.imgur.com/PO6ahRU.jpg

**Modlist version**
1.0

**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed for v1.0.2
