### ISSUE TITLE
Sabertooth cats Ragdoll Spam

### ISSUE THREAD

**Issue by ThrasherGX** [jdsmith2816/eldersouls#50]
**Describe the bug**
The Sabertooth cat has a powerfull ragdoll attack.  If it hits you with it, it will often keep using it before you have a chance to get up again.  Oftentimes, you will end up dead before you can even get out of the ragdoll animation

**To Reproduce**

1. Let the sabertooth smack you
2. Once ragdolled, try to escape.  You usually will not be able to.

**Expected behavior**
Ragdoll attacks should have a long cooldown so that they cannot be abused.  This applies to player and mobs both/

**Modlist version**
1.0.3
**Did you add any additional mods?**
Simple Lock On

**Comment by jdsmith2816** [comment]
Fixed in 1.3.1
