### ISSUE TITLE
Disable Dark Souls Leveling for Crafting Skills Only

### ISSUE THREAD

**Issue by ThrasherGX** [jdsmith2816/eldersouls#51]
**Request**
Disable the Dark Souls Leveling system for Crafting skills only.  This way players wont be faced with such a huge cost for leveling up their crafting skills, but still have the dark souls experience for combat related skills.

**Additional context**
Personally, I have been reluctant to level my crafting skills, because doing so costs a lot of money and makes my combat skills more expensive to level at the same time.  And by lategame, the cost to level a completely new skill would likely be prohibitively high.  This change to a hybrid system should help alleviate the catch 22 of the current system regarding crafting skills.

**Comment by jdsmith2816** [comment]
Done in 1.0.4
