### ISSUE TITLE
Black Mage Armor SE Mod

### ISSUE THREAD

**Issue by ThrasherGX** [jdsmith2816/eldersouls#52]
**Request**
Add the Black Mage Armor SE mod.  There are not really very many magey armor/robe sets added in this mod (or anywhere really), and black mage is one of the few decent ones.

**Additional context**
https://www.nexusmods.com/skyrimspecialedition/mods/356 <- Source for Black mage mod.

**Comment by jdsmith2816** [comment]
Done in 1.0.4
