### ISSUE TITLE
Tomebound

### ISSUE THREAD

**Issue by Squatchyfz** [jdsmith2816/eldersouls#54]
**Request**
Basically a mod that adds a bunch of spell tomes like the Spell Tomes DLC for Oblivion did. I think this would round out the magic in the pack, which doesn't seem to have gotten a ton of attention
**Additional context**
https://www.nexusmods.com/skyrimspecialedition/mods/21403

**Comment by jdsmith2816** [comment]
Mysticism adds over 200 new spells including master level ones and there is some overlap with what tomebound provides.  I think between Mysticism, Forgotten Magic and the variou spells added by other content mods we're in an ok place.
