### ISSUE TITLE
Halamshiral Missing Textures

### ISSUE THREAD

**Issue by ThrasherGX** [jdsmith2816/eldersouls#55]
**Describe the bug**
Two tools on the Alchemy/Enchanting bench on the first floor of Halamshiral are missing textures.

**Screenshots**
![enb2020_5_9_16_16_35](https://user-images.githubusercontent.com/38668000/81485187-cd512280-9210-11ea-8355-10d184757cae.png)
![enb2020_5_9_16_16_33](https://user-images.githubusercontent.com/38668000/81485191-d3470380-9210-11ea-8572-fbf6f0825d4b.png)

**Modlist version**
1.0.3
**Did you add any additional mods?**
Simple Lock On

**Comment by jdsmith2816** [comment]
Resolved in 1.0.4
