### ISSUE TITLE
Hilde Missing Arms

### ISSUE THREAD

**Issue by ThrasherGX** [jdsmith2816/eldersouls#56]
**Describe the bug**
The NPC Hilde in Riverwood is missing her forearms

**Screenshots**
![enb2020_5_11_18_59_32](https://user-images.githubusercontent.com/38668000/81623645-b994f000-93b9-11ea-8ab9-cf7b7b983059.png)

**Modlist version**
1.1.1
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
@ThrasherGX Is this happening to ALL elderly females?  Hilde and Tilma are elderly..
