### ISSUE TITLE
Auto Loot Gold and Gold Souls

### ISSUE THREAD

**Issue by ChrisJordan92** [jdsmith2816/eldersouls#57]
Auto loot gold only from corpses upon killing them. This way it feels more like experience rather than gold.

Also, is it possible to replace gold found in containers with souls which grant you gold upon using them? For example, a lesser soul gives you 20 gold, a potent soul gives you 100 gold and so on.

**Comment by jdsmith2816** [comment]
First part of this was fixed in 1.1.3 

Feel free to open up a second feature request to track the second idea.  I'm not opposed to it but I'm just not for sure yet how I want to deal with soul like items.
