### ISSUE TITLE
Pre-placed Corpses contain Bonus Gold

### ISSUE THREAD

**Issue by ThrasherGX** [jdsmith2816/eldersouls#58]
**Describe the bug**
The bonus gold added to each enemy is also added to pre-placed corpses that are already dead when the player encounters them.

**Expected behavior**
This will likely end up giving the player significantly more gold than is intended, for essentially no effort.

**Modlist version**
1.1.1
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 1.1.2 for the majority of cases
