### ISSUE TITLE
Whiterun Lod issues

### ISSUE THREAD

**Issue by bishop1824** [jdsmith2816/eldersouls#59]
Bright white lod on certain items around the whiterun area

**To Reproduce**
coc whiterun and tfc 
lod returns to normal upon getting close or clicking on it in console

1. Go to 'towards the farm where the companions fight the giants and chillfurrow farm'
2. Do '...'

**Expected behavior**

**Screenshots**
![20200512123823_1](https://user-images.githubusercontent.com/65206514/81632771-720c7380-944e-11ea-8c84-f8a0464b0e40.jpg)
![20200512123840_1](https://user-images.githubusercontent.com/65206514/81632777-746ecd80-944e-11ea-881d-f65c02d6f119.jpg)
![20200512123851_1](https://user-images.githubusercontent.com/65206514/81632779-75076400-944e-11ea-8685-1c2ca248d87b.jpg)
![20200512123917_1](https://user-images.githubusercontent.com/65206514/81632783-75076400-944e-11ea-8384-0b05b02ba0ce.jpg)
![20200512123935_1](https://user-images.githubusercontent.com/65206514/81632786-759ffa80-944e-11ea-94a6-ec2ca6b0d6d8.jpg)
![20200512124017_1](https://user-images.githubusercontent.com/65206514/81632788-76389100-944e-11ea-9877-14a4f1a80566.jpg)
![20200512124050_1](https://user-images.githubusercontent.com/65206514/81632789-76d12780-944e-11ea-9100-6cba440827fc.jpg)

**Modlist version**

**Did you add any additional mods?**
just a change of enb and teamtals darksouls pack

**Comment by jdsmith2816** [comment]
Fixed in v1.1.2
