### ISSUE TITLE
Remove Crafting skills from the Purchase Skill Level screen

### ISSUE THREAD

**Issue by ThrasherGX** [jdsmith2816/eldersouls#60]
**Describe the bug**
Crafting skills are currently able to be selected on the skill level up screen after sleeping.  Since these skills have been reverted to vanilla leveling, they should not be able to be purchased when sleeping.

**Modlist version**
1.1.1
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
I think this is a feature not a bug.
