### ISSUE TITLE
Skills leveling 

### ISSUE THREAD

**Issue by SerDagron** [jdsmith2816/eldersouls#62]
**Describe the bug**
Skills are increasing very rapidly outside of the new gold based system. However this did not start happening until I killed the Giant Frostbite spider in Bleak Falls Barrow.
Sneak, Destruction and Restoration are the skills I have noticed doing this but there may be others.

**To Reproduce**
Create new character (select hunter in the woods for ease)
Head to Bleak Falls Barrow.
Progress until you find Arvel and the Giant spider.
After killing the spider, use the Flames spell on Arvel and Destruction should level up at least once.
Start sneaking into the next room where the sleeping Draugr are.
Sneak skill will start increasing very rapidly.

**Expected behavior**
No skills should be leveling up.

**Modlist version**
1.1.1

**Did you add any additional mods?**
Replaced Smooth Cam with 3PCO.
Disabled Bow Before the Dead.

**Comment by jdsmith2816** [comment]
Unable to reproduce. Feel free to re-open if you're able to reproduce still on 1.1.2  Maybe i'm doing something wrong while testing.

**Comment by SerDagron** [comment]
Not to worry, you weren't doing something wrong in testing, I haven't been able to reproduce it either. I reckon it's something to do with the Elder Scroll save function though, so far I can only get this to happen after using a scroll, but not reliably.

I have a single save file that has this issue 100% of the time, but I can't reproduce it on other saves with the same or character or new charcters.

Will re-open and update the description if I can find a way to reliably reproduce it on new characters.
