### ISSUE TITLE
Broken visuals on specific Ghost

### ISSUE THREAD

**Issue by KarMagick** [jdsmith2816/eldersouls#63]
**Describe the bug**
A specific ghost (I've only seen one thus far) has very peculiar visuals covering the entire screen with whole-screen flashing, becoming black, purple, white, preventing the player from seeing for most of the encounter with it.

**To Reproduce**

1. Go to 'Abandoned Prison', the one where your new character spawns,
2. Pick the "I want to escape from this cell." option from Lady Mara,
3. Exit your cell and encounter the first ghost of the prison, in the cell on the left.
4. Upon detecting you he will unsheathe his weapons (a staff and a sword) and the visuals will begin.

**Expected behavior**
Can't put it into words much further than what I put above and in the screenshot below, but here are the IDs:
Base form ID: 000B1F96
Ref form ID: 000590F1

**Screenshots**
https://media.discordapp.net/attachments/704708621732151547/709826555630714890/unknown.png?width=1250&height=677 - Weird visuals
http://prntscr.com/sfjv2b - Console page

**Modlist version**
1.1.1

**Did you add any additional mods?**
None.

**Comment by jdsmith2816** [comment]
Unable to reproduce in 1.1.3
Feel free to re-open with new evidence if it still happens on latest.
