### ISSUE TITLE
Bugged Texture in Ragged Flaggon

### ISSUE THREAD

**Issue by seraphimsake** [jdsmith2816/eldersouls#64]
This is a bugged texture located in the Ragged Flagon on the sign above the barkeep

To Reproduce:
New Character ->New Member of Guild->Thieves Guild

https://imgur.com/a/ACXnwjk
ECTV Merge is the last reference.

I will "markfordelete" for my personal play-through until fixed.

Modlist version 1.1.1

No Additional Mods

**Comment by jdsmith2816** [comment]
Fixed in 1.1.2
