### ISSUE TITLE
Controller does not work

### ISSUE THREAD

**Issue by shazdeh** [jdsmith2816/eldersouls#66]
**Describe the bug**
When using the modlist, the controller does not work, the game still accepts input from mouse and keyboard which normally when controller is connected they stop. When trying a different modlist or with vanilla game, the controller works as expected.

**To Reproduce**
Connect a controller to PC. Run the game.

**Modlist version**
1.1.1

**Comment by jdsmith2816** [comment]
The controller definitely works;  you either have a buggered install or have done something strange.

**Comment by shazdeh** [comment]
Thanks for checking.
I updated to 1.1.2 and tested again. Vanilla Skyrim works, tested using [Cupid](https://www.wabbajack.org/modlist/cupid) modlist, also works. But with Elder Souls it doesn't recognize it. I have not tampered with the load order or any settings.

Was wondering if there's a way to debug this? Like, any log files to look into? This is certainly caused by one of the mods, any of them I could disable temporarily perhaps?
