### ISSUE TITLE
Wabbajack is spitting out an error

### ISSUE THREAD

**Issue by Buft537** [jdsmith2816/eldersouls#67]
**Describe the bug**
After multiple tries (5) i get always the same error, even after trying to update from 1.1.1 to 1.1.2

**To Reproduce**

1. Go to 'https://www.wabbajack.org/'
2. Do 'download Elder Souls'

**Expected behavior**
Completion of installation.
**Screenshots**
![Wabbajack 13 05 2020 14_38_38](https://user-images.githubusercontent.com/65291254/81814520-2f6b9980-9529-11ea-840a-3e55cd799a59.png)

**Modlist version**
1.1.1 and 1.1.2
**Did you add any additional mods?**
No

I hope this is not a stupid error on my part.

**Comment by rshackleton** [comment]
I had the same error, I ended up re-downloading the mod list and it didn't happen on another attempt. However, I had also manually downloaded the mod mentioned in #61 here which might have been the cause of the issue?

**Comment by Buft537** [comment]
Okay, thanks. I have gone through the pain of downloading everything without nexus premium, so I don't have the nerves to do it again. Guess I have to pay some money, but I think it is worth it.

**Comment by jdsmith2816** [comment]
This was caused by you having an out o fdate WJ version.  If you kept your downloads folder it should be trivial to install if you update WJ to latest.
