### ISSUE TITLE
Skyrim Unbound Reborn

### ISSUE THREAD

**Issue by rshackleton** [jdsmith2816/eldersouls#68]
**Request**
An alternative, alternate start mod to replace Live Another Life.

https://www.nexusmods.com/skyrimspecialedition/mods/27962

The mod offers a lot more control over the starting character, equipment, spells etc.

Perhaps there could be a way to create Souls-like presets to choose from based on the Unbound mod?

**Additional context**
N/A

**Comment by jdsmith2816** [comment]
Unfortunately we can't use Unbound due to... reasons. Personally I much prefer Skyrim Unbound which is why it's used in RGE.

**Comment by rshackleton** [comment]
Curious, does that apply Unbound Reborn or just Unbound?

**Comment by jdsmith2816** [comment]
It applies to both.
