### ISSUE TITLE
Combat Gameplay Overhaul SE

### ISSUE THREAD

**Issue by rshackleton** [jdsmith2816/eldersouls#69]
**Request**
An alternative combat mod, the stand out feature that would make the modlist more Souls-like would be the ability to switch between 1h and 2h stances on weapons.

https://www.nexusmods.com/skyrimspecialedition/mods/33767

**Additional context**
The mod has a lot of overlap with other mods in the list as it includes combat animations, combat dodging/rolling, etc.

**Comment by jdsmith2816** [comment]
I enjoy CGO (it's in RGE after all) but it really throws balance out of whack.  If at some point CGO becomes more modular and I can choose to only use the features I care about then CGO would come back.
