### ISSUE TITLE
Arcane Weapon Greatsword form missing texture

### ISSUE THREAD

**Issue by ThrasherGX** [jdsmith2816/eldersouls#70]
**Describe the bug**
The greatsword form of the Forgotten Magic spell Arcane Weapon is missing its texture and special bound weapon effect (if it has one?)

**Screenshots**
![ScreenShot0](https://user-images.githubusercontent.com/38668000/81873913-56829500-9542-11ea-812a-ae837222da11.png)

**Modlist version**
1.1.2
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
I think this is working as intended.  The bound dagger has effects that make it look like ab ound weapon but the other 3 have completely different effects assigned and they're custom effects tot he mod.  I think they are meant to make it look kind of ghostly.
