### ISSUE TITLE
Inventory-invisible items

### ISSUE THREAD

**Issue by KarMagick** [jdsmith2816/eldersouls#73]
**Describe the bug**
Certain items can be picked up but not seen in the inventory, taking up precious carry weight while being unusable. The two items I've managed to identify so far are "Arrow - Iron" (0001397D) and "Iron Shield" (00012EB6). These items are visible when in a container or vendor, but become invisible in the player inventory. They still show up in crafting menus, and can be use for it however.

**To Reproduce**

1. Open console
2. Spawn in either item via player.additem or player.placeatme
2.5 Pick them up if spawned in via player.placeatme
3, Check your inventory and realize these items are nowhere to be found

**Expected behavior**
Items should either be visible in the inventory, or the player should be unable to pick these up if they're not intended to be useable.

**Screenshots**
N/A

**Modlist version**
1.1.2

**Did you add any additional mods?**
None.

**Comment by swampfox2** [comment]
> **Describe the bug**
> Certain items can be picked up but not seen in the inventory, taking up precious carry weight while being unusable. The two items I've managed to identify so far are "Arrow - Iron" (0001397D) and "Iron Shield" (00012EB6). These items are visible when in a container or vendor, but become invisible in the player inventory. They still show up in crafting menus, and can be use for it however.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Open console
> 2. Spawn in either item via player.additem or player.placeatme
>    2.5 Pick them up if spawned in via player.placeatme
>    3, Check your inventory and realize these items are nowhere to be found
> 
> **Expected behavior**
> Items should either be visible in the inventory, or the player should be unable to pick these up if they're not intended to be useable.
> 
> **Screenshots**
> N/A
> 
> **Modlist version**
> 1.1.2
> 
> **Did you add any additional mods?**
> None.

#3 The Ash Waraxe - not finding it in inventory.

**Comment by jdsmith2816** [comment]
`Unable to reproduce KarMagick's issues. The Ash Waraxe however is not invisible in your inventory but it DOES go away after you remove it.  I'm unsure if this is acting as intended or a bug.. Need to do some digging.  The `Dense Ash Waraxe` and `Volcanic Ash Waraxe` do not disappear on unequip so...
