### ISSUE TITLE
Missing ship at Raven Rock dock

### ISSUE THREAD

**Issue by swampfox2** [jdsmith2816/eldersouls#74]
The main ship that takes you back to Skyrim from Raven Rock dock is missing. The deck hands are mopping on top of the water. 

LAL spawned me in Raven Rock, and when I went to the boat it was missing. 

![ScreenShot0](https://user-images.githubusercontent.com/65110997/81903859-02020880-9588-11ea-8775-5461c12a6c48.png)

Version 1.1.2

No additional mods added

**Comment by jdsmith2816** [comment]
Unable to reproduce in 1.1.3
