### ISSUE TITLE
Send charlie to get rid of the rats

### ISSUE THREAD

**Issue by NotTotal** [jdsmith2816/eldersouls#77]
They've infected riften, its a big problem jd
![2020 05 05-02 17_01](https://user-images.githubusercontent.com/22380834/81973984-c5f79380-95d9-11ea-8c20-129563fdc67b.png)

**Comment by NotTotal** [comment]
[https://www.youtube.com/watch?v=kIWss-_5HGM](https://www.youtube.com/watch?v=kIWss-_5HGM) relevant

**Comment by jdsmith2816** [comment]
Fixed in 1.1.4
