### ISSUE TITLE
Invisible Companion Werewolves

### ISSUE THREAD

**Issue by rshackleton** [jdsmith2816/eldersouls#81]
**Describe the bug**
During the Companion quest line the various companions are invisible when in werewolf form. This happened to both Farkas during the [Proving Honor](https://elderscrolls.fandom.com/wiki/Proving_Honor) quest and Aela during the [The Silver Hand](https://elderscrolls.fandom.com/wiki/The_Silver_Hand) quest.

**To Reproduce**

1. Start the companions' questline.
2. Reach the Proving Honor quest.
3. Reach the section when Farkas transforms, he will be invisible.

**Expected behavior**
The werewolf forms should be visible.

**Screenshots**
Couldn't click on them in werewolf form as they were invisible. Here is a screenshot during The Silver Hand quest.

![ScreenShot0](https://user-images.githubusercontent.com/13448395/82125846-a3fc3d80-97a0-11ea-8062-8f1f3aea6b00.png)

**Modlist version**
v1.1.1

**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment]
I think this is fixed in 1.1.7 (should release tonight) but I'm gonna leave this open until I have time to verify or you report back that it's working.
