### ISSUE TITLE
Random tree in Millwater Retreat

### ISSUE THREAD

**Issue by rshackleton** [jdsmith2816/eldersouls#82]
**Describe the bug**
There is a tree in Millwater Retreat that is blocking the stairs, seems out of place.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Millwater Retreat

**Expected behaviour**
The tree shouldn't be blocking the stairs.

**Screenshots**
![image](https://user-images.githubusercontent.com/13448395/82129540-a15b1180-97bb-11ea-9d80-151ff39460ed.png)

**Modlist version**
1.1.1

**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment]
Fixed in 1.1.11
