### ISSUE TITLE
Fortification talent Rank 1 Gives Wrong Armor Amount

### ISSUE THREAD

**Issue by ThrasherGX** [jdsmith2816/eldersouls#83]
**Describe the bug**
The Fortification rank 1 talent in Alteration gives 50 armor when unarmored, but the description says it gives 75.

**Expected behavior**
The description and actual amount should match.

**Modlist version**
1.1.4

**Comment by jdsmith2816** [comment]
This is actually an Adamant perk description issue.  It's intended to be 50 when using Adamant with Balde & blunt but the description wasn't updated.  I informed Simon and fixed it in the ESGP for now.

Fixed in 1.1.11
