### ISSUE TITLE
Leveling Currency and Gold Combined

### ISSUE THREAD

**Issue by grmakrig** [jdsmith2816/eldersouls#86]
Hey there,

With the most recent patch, my store gold and leveling currency have been combined into one currency. I'd like to confirm this is intentional.

Apologies if this was always the case and I didn't notice - my last save file was just a few hours in but I thought the currencies were separate.

**To reproduce:**
Start a new character with Vanilla background. Kill an enemy. Use gold in a shop.

**Modlist version**
1.1.3

**Did you add any additional mods?**
No

**Comment by grmakrig** [comment]
I'm an idiot - Dark souls uses the same currency for leveling and stores, so I assume this mod does too and I missed that earlier.

**Comment by jdsmith2816** [comment]
No problem.  Sorry that I didn't see this but yes.. It hsould all be one currency.
