### ISSUE TITLE
Massive Script Proliferation in Save File

### ISSUE THREAD

**Issue by ThrasherGX** [jdsmith2816/eldersouls#87]
**Describe the bug**
There are a constantly increasing number of instances of ElderSouls_Death_GoldGrantTokenScript.
As of time of writing my current save has 215 instances.  A save from an hour before, was at 194.
The first save I checked after updating to the gold script version of the mod has 26.  I am also noticing increasing frequency of CTDs, usually on change of area.

**Screenshots**
Shortly After updating to Script gold version
![image](https://user-images.githubusercontent.com/38668000/82162058-47b02100-9867-11ea-8c5e-5d7f15753ceb.png)
Current Save
![image](https://user-images.githubusercontent.com/38668000/82162080-6adad080-9867-11ea-8dfa-b4d7f2205de7.png)

**Did you add any additional mods?**
No

**Comment by ThrasherGX** [comment]
Upon further thinking, I would guess that this issue is a result of the particular enemies in Nurndural (Dwemer ruin beneath the Clockwork Castle).  The enemies there reanimate themselves after a certain amount of time, with no limit.  Each time they are killed they grant gold, but they are technically the same enemy and I believe their bodies are never cleaned up, as they are never really dead.

**Comment by jdsmith2816** [comment]
Fixed in v1.3.1
