### ISSUE TITLE
Repeated CTD in The Bee and Barb in Riften

### ISSUE THREAD

**Issue by rshackleton** [jdsmith2816/eldersouls#88]
**Describe the bug**
A short time after entering The Bee and Barb the game crashes.

**To Reproduce**

1. Go to The Bee and Barb
2. Move around or wait around 10-20 seconds

**Expected behavior**
The game doesn't crash!

**Screenshots**
Here is a crash log. 

[Crash_2020_5_17_21-47-35.txt](https://github.com/jdsmith2816/eldersouls/files/4641250/Crash_2020_5_17_21-47-35.txt)

**Modlist version**
1.1.4

**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment]
Thanks.  I think I know how to fix this but next release is a ways out.  I'll prioritize getting this fix included though.

**Comment by jdsmith2816** [comment]
This will be a while before fixing for various reasons.  I think it'll be resolved when I get done rebuilding the ECTV merge

**Comment by jdsmith2816** [comment]
Fixed in 1.3
