### ISSUE TITLE
NavMesh cell -17, -12

### ISSUE THREAD

**Issue by rb-evans** [jdsmith2816/eldersouls#93]
navmesh seems to be missing between accursed cave and fellburg around cell -17,-12.
walk from one location to the next with followers. they stop. fast travel to other location, try walking with them the other way - also stop.

**Comment by jdsmith2816** [comment]
Thanks!  I'll make sure this is fixed during the next update to the cities and homes merge.

**Comment by jdsmith2816** [comment]
Fixed in 1.3
