### ISSUE TITLE
Missing Ground at Shoal's Rest Farm

### ISSUE THREAD

**Issue by Shanomatic** [jdsmith2816/eldersouls#99]
**Describe the bug**
There appears to be some missing ground infront of Shoal's Rest Farm, north of Rorikstead 

**To Reproduce**

1. Go to Shoal's Rest Farm
2. Examine ground

**Expected behavior**
There should be some ground here.

**Screenshots**
![20200525113050_1](https://user-images.githubusercontent.com/65898197/82826557-5efc9900-9e7b-11ea-953f-50f9dfdbf172.jpg)

**Modlist version**
1.1.7
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 1.3
